using System;
using System.Collections.Generic;
using WordParserCore.Helpers;

namespace WordParserCore
{
    public sealed record StyleInfo(string DisplayName, bool IsAmendment);

    public static class StyleLibraryMapper
	{
		public static readonly IReadOnlyDictionary<string, string> StyleMap = 
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "2TIRpodwjnytiret", "2TIR – podwójny tiret" },
            { "ARTartustawynprozporzdzenia", "ART(§) – art. ustawy (§ np. rozporządzenia)" },
            { "BEZWERSALIKW", "_BEZ_WERSALIKÓW_" },
            { "CYTcytatnpprzysigi", "CYT – cytat np. przysięgi" },
            { "CZKSIGAoznaczenieiprzedmiotczcilubksigi", "CZĘŚĆ(KSIĘGA) – oznaczenie i przedmiot części lub księgi" },
            { "CZWSP2TIRczwsplnapodwjnychtiret", "CZ_WSP_2TIR – część wspólna podwójnych tiret" },
            { "CZWSPLITODNONIKAczwspliterodnonika", "CZ_WSP_LIT_ODNOŚNIKA – część wsp. liter odnośnika" },
            { "CZWSPLITczwsplnaliter", "CZ_WSP_LIT – część wspólna liter" },
            { "CZWSPP1wTABELIczwsppoziomu1numeracjiwtabeli", "CZ_WSP_P1_w_TABELI – część wsp. poziomu 1 numeracji w tabeli" },
            { "CZWSPP2wTABELIczwsppoziomu2numeracjiwtabeli", "CZ_WSP_P2_w_TABELI – część wsp. poziomu 2 numeracji w tabeli" },
            { "CZWSPP3wTABELIczwsppoziomu3numeracjiwtabeli", "CZ_WSP_P3_w_TABELI – część wsp. poziomu 3 numeracji w tabeli" },
            { "CZWSPP4wTABELIczwsppoziomu4numeracjiwtabeli", "CZ_WSP_P4_w_TABELI – część wsp. poziomu 4 numeracji w tabeli" },
            { "CZWSPPKTODNONIKAczwsppunkwodnonika", "CZ_WSP_PKT_ODNOŚNIKA – część wsp. punków odnośnika" },
            { "CZWSPPKTczwsplnapunktw", "CZ_WSP_PKT – część wspólna punktów" },
            { "CZWSPPPKTOTJczwsppodpunktwwobwieszczeniutekstujednolitego", "CZ_WSP_PPKT_OTJ – część wsp. podpunktów w obwieszczeniu tekstu jednolitego" },
            { "CZWSPTIRczwsplnatiret", "CZ_WSP_TIR – część wspólna tiret" },
            { "DATAAKTUdatauchwalenialubwydaniaaktu", "DATA_AKTU – data uchwalenia lub wydania aktu" },
            { "DATAOTJdatawydaniaobwieszczeniatekstujednolitego", "DATA_OTJ – data wydania obwieszczenia tekstu jednolitego" },
            { "IDKindeksdolnyikursywa", "_ID_K_ – indeks dolny i kursywa" },
            { "IDPKindeksdolnyipogrugieniekursywa", "_ID_P_K_ – indeks dolny i pogrugienie kursywa" },
            { "IDPindeksdolnyipogrubienie", "_ID_P_ – indeks dolny i pogrubienie" },
            { "IDindeksdolny", "_ID_ – indeks dolny" },
            { "IGKindeksgrnyikursywa", "_IG_K_ – indeks górny i kursywa" },
            { "IGPKindeksgrnyipogrubieniekursywa", "_IG_P_K_ – indeks górny i pogrubienie kursywa" },
            { "IGPindeksgrnyipogrubienie", "_IG_P_ – indeks górny i pogrubienie" },
            { "IGindeksgrny", "_IG_ – indeks górny" },
            { "IIGPindeksgrnyindeksugrnegoipogrubienie", "_IIG_P_ – indeks górny indeksu górnego i pogrubienie" },
            { "IIGindeksgrnyindeksugrnego", "_IIG_ – indeks górny indeksu górnego" },
            { "Kkursywa", "_K_ – kursywa" },
            { "LEGWMATFIZCHEMlegendawzorumatfizlubchem", "LEG_W_MAT(FIZ|CHEM) – legenda wzoru mat. (fiz. lub chem.)" },
            { "LITODNONIKAliteraodnonika", "LIT_ODNOŚNIKA – litera odnośnika" },
            { "LITlitera", "LIT – litera" },
            { "NAZORGWPOROZUMIENIUnazwaorganuwporozumieniuzktrymaktjestwydawany", "NAZ_ORG_W_POROZUMIENIU – nazwa organu w porozumieniu z którym akt jest wydawany" },
            { "NAZORGWYDnazwaorganuwydajcegoprojektowanyakt", "NAZ_ORG_WYD – nazwa organu wydającego projektowany akt" },
            { "NIEARTTEKSTtekstnieartykuowanynppodstprawnarozplubpreambua", "NIEART_TEKST – tekst nieartykułowany (np. podst. prawna rozp. lub preambuła)" },
            { "ODNONIKSPECtreodnonikadoodnonika", "ODNOŚNIK_SPEC – treść odnośnika do odnośnika" },
            { "ODNONIKtreodnonika", "ODNOŚNIK – treść odnośnika" },
            { "OZNPROJEKTUwskazaniedatylubwersjiprojektu", "OZN_PROJEKTU – wskazanie daty lub wersji projektu" },
            { "OZNRODZAKTUtznustawalubrozporzdzenieiorganwydajcy", "OZN_RODZ_AKTU – tzn. ustawa lub rozporządzenie i organ wydający" },
            { "OZNZACZNIKAwskazanienrzacznika", "OZN_ZAŁĄCZNIKA – wskazanie nr załącznika" },
            { "P1wTABELIpoziom1numeracjiwtabeli", "P1_w_TABELI – poziom 1 numeracji w tabeli" },
            { "P2wTABELIpoziom2numeracjiwtabeli", "P2_w_TABELI – poziom 2 numeracji w tabeli" },
            { "P3wTABELIpoziom3numeracjiwtabeli", "P3_w_TABELI – poziom 3 numeracji w tabeli" },
            { "P4wTABELIpoziom4numeracjiwtabeli", "P4_w_TABELI – poziom 4 numeracji w tabeli" },
            { "PKTODNONIKApunktodnonika", "PKT_ODNOŚNIKA – punkt odnośnika" },
            { "PKTOTJpunktobwieszczeniatekstujednolitegonp1", "PKT_OTJ – punkt obwieszczenia tekstu jednolitego np. \"1.\"" },
            { "PKTpunkt", "PKT – punkt" },
            { "PKpogrubieniekursywa", "_P_K_ – pogrubienie kursywa" },
            { "PPKTOTJpodpunktwobwieszczeniutekstujednolitegonp1", "PPKT_OTJ – podpunkt w obwieszczeniu tekstu jednolitego np. \"1)\"" },
            { "Ppogrubienie", "_P_ – pogrubienie" },
            { "ROZDZODDZOZNoznaczenierozdziauluboddziau", "ROZDZ(ODDZ)_OZN – oznaczenie rozdziału lub oddziału" },
            { "ROZDZODDZPRZEDMprzedmiotregulacjirozdziauluboddziau", "ROZDZ(ODDZ)_PRZEDM – przedmiot regulacji rozdziału lub oddziału" },
            { "SKARNsankcjakarnawszczeglnociwKodeksiekarnym", "S_KARN – sankcja karna w szczególności w Kodeksie karnym" },
            { "TEKSTwTABELIWYRODKOWANYtekstwyrodkowanywpoziomie", "TEKST_w_TABELI_WYŚRODKOWANY – tekst wyśrodkowany w poziomie" },
            { "TEKSTwTABELItekstzwcitympierwwierszem", "TEKST_w_TABELI – tekst z wciętym pierw. wierszem" },
            { "TIRtiret", "TIR – tiret" },
            { "TYTDZOZNoznaczenietytuulubdziau", "TYT(DZ)_OZN – oznaczenie tytułu lub działu" },
            { "TYTDZPRZEDMprzedmiotregulacjitytuulubdziau", "TYT(DZ)_PRZEDM – przedmiot regulacji tytułu lub działu" },
            { "TYTTABELItytutabeli", "TYT_TABELI – tytuł tabeli" },
            { "TYTUAKTUprzedmiotregulacjiustawylubrozporzdzenia", "TYTUŁ_AKTU – przedmiot regulacji ustawy lub rozporządzenia" },
            { "TYTUOTJprzedmiotobwieszczeniatekstujednolitego", "TYTUŁ_OTJ – przedmiot obwieszczenia tekstu jednolitego" },
            { "USTustnpkodeksu", "UST(§) – ust. (§ np. kodeksu)" },
            { "WMATFIZCHEMwzrmatfizlubchem", "W_MAT(FIZ|CHEM) – wzór mat. (fiz. lub chem.)" },
            { "Z2TIR2TIRwLITzmpodwtirwlitpodwjnymtiret", "Z_2TIR/2TIR_w_LIT – zm. podw. tir. w lit. podwójnym tiret" },
            { "Z2TIR2TIRwPKTzmpodwtirwpktpodwjnymtiret", "Z_2TIR/2TIR_w_PKT – zm. podw. tir. w pkt podwójnym tiret" },
            { "Z2TIR2TIRwTIRzmpodwtirwtirpodwjnymtiret", "Z_2TIR/2TIR_w_TIR – zm. podw. tir. w tir. podwójnym tiret" },
            { "Z2TIR2TIRzmpodwtirpodwjnymtiret", "Z_2TIR/2TIR – zm. podw. tir. podwójnym tiret" },
            { "Z2TIRARTzmartpodwjnymtiret", "Z_2TIR/ART(§) – zm. art. (§) podwójnym tiret" },
            { "Z2TIRCYTzmcytatunpprzysigipodwjnymtiret", "Z_2TIR/CYT – zm. cytatu np. przysięgi podwójnym tiret" },
            { "Z2TIRCZWSP2TIRwLITzmczciwsppodwtirwlitpodwjnymtiret", "Z_2TIR/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. podwójnym tiret" },
            { "Z2TIRCZWSP2TIRwPKTzmczciwsppodwtirwpktpodwjnymtiret", "Z_2TIR/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt podwójnym tiret" },
            { "Z2TIRCZWSP2TIRwTIRzmczciwsppodwtirwtiretpodwjnymtiret", "Z_2TIR/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tiret podwójnym tiret" },
            { "Z2TIRCZWSP2TIRzmczciwsppodwtirpodwjnymtiret", "Z_2TIR/CZ_WSP_2TIR – zm. części wsp. podw. tir. podwójnym tiret" },
            { "Z2TIRCZWSPLITwPKTzmczciwsplitwpktpodwjnymtiret", "Z_2TIR/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt podwójnym tiret" },
            { "Z2TIRCZWSPLITzmczciwsplitpodwjnymtiret", "Z_2TIR/CZ_WSP_LIT – zm. części wsp. lit. podwójnym tiret" },
            { "Z2TIRCZWSPPKTzmczciwsppktpodwjnymtiret", "Z_2TIR/CZ_WSP_PKT – zm. części wsp. pkt podwójnym tiret" },
            { "Z2TIRCZWSPTIRwLITzmczciwsptirwlitpodwjnymtiret", "Z_2TIR/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. podwójnym tiret" },
            { "Z2TIRCZWSPTIRwPKTzmczciwsptirwpktpodwjnymtiret", "Z_2TIR/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt podwójnym tiret" },
            { "Z2TIRCZWSPTIRzmczciwsptirpodwjnymtiret", "Z_2TIR/CZ_WSP_TIR – zm. części wsp. tir. podwójnym tiret" },
            { "Z2TIRFRAGMzmnpwprdowyliczeniapodwjnymtiret", "Z_2TIR/FRAGM – zm. np. wpr. do wyliczenia podwójnym tiret" },
            { "Z2TIRLEGWMATFIZCHEMzmlegendywzorumatfizlubchempodwjnymtiret", "Z_2TIR/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) podwójnym tiret" },
            { "Z2TIRLITwPKTzmlitwpktpodwjnymtiret", "Z_2TIR/LIT_w_PKT – zm. lit. w pkt podwójnym tiret" },
            { "Z2TIRLITzmlitpodwjnymtiret", "Z_2TIR/LIT – zm. lit. podwójnym tiret" },
            { "Z2TIRPKTzmpktpodwjnymtiret", "Z_2TIR/PKT – zm. pkt podwójnym tiret" },
            { "Z2TIRROZDZODDZOZNzmoznrozdzoddzpodwjnymtiret", "Z_2TIR/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) podwójnym tiret" },
            { "Z2TIRROZDZODDZPRZEDMzmprzedmrozdzoddzpodwjnymtiret", "Z_2TIR/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) podwójnym tiret" },
            { "Z2TIRSKARNzmianasankcjikarnejpodwjnymtiret", "Z_2TIR/S_KARN – zmiana sankcji karnej podwójnym tiret" },
            { "Z2TIRTIRwLITzmtirwlitpodwjnymtiret", "Z_2TIR/TIR_w_LIT – zm. tir. w lit. podwójnym tiret" },
            { "Z2TIRTIRwPKTzmtirwpktpodwjnymtiret", "Z_2TIR/TIR_w_PKT – zm. tir. w pkt podwójnym tiret" },
            { "Z2TIRTIRzmtirpodwjnymtiret", "Z_2TIR/TIR – zm. tir. podwójnym tiret" },
            { "Z2TIRUSTzmustpodwjnymtiret", "Z_2TIR/UST(§) – zm. ust. (§) podwójnym tiret" },
            { "Z2TIRWMATFIZCHEMzmwzorumatfizlubchempodwjnymtiret", "Z_2TIR/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) podwójnym tiret" },
            { "Z2TIRwLITzmpodwtirwlitartykuempunktem", "Z/2TIR_w_LIT – zm. podw. tir. w lit. artykułem (punktem)" },
            { "Z2TIRwPKTzmpodwtirwpktartykuempunktem", "Z/2TIR_w_PKT – zm. podw. tir. w pkt artykułem (punktem)" },
            { "Z2TIRwTIRzmpodwtirwtirartykuempunktem", "Z/2TIR_w_TIR – zm. podw. tir. w tir. artykułem (punktem)" },
            { "Z2TIRzmpodwtirartykuempunktem", "Z/2TIR – zm. podw. tir. artykułem (punktem)" },
            { "ZARTzmartartykuempunktem", "Z/ART(§) – zm. art. (§) artykułem (punktem)" },
            { "ZCYTzmcytatunpprzysigiartykuempunktem", "Z/CYT – zm. cytatu np. przysięgi artykułem (punktem)" },
            { "ZCZCIKSIGIzmozniprzedmczciksigiartykuempunktem", "Z/CZĘŚCI(KSIĘGI) – zm. ozn. i przedm. części (księgi) artykułem (punktem)" },
            { "ZCZWSP2TIRwLITzmczciwsppodwtirwlitartykuempunktem", "Z/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. artykułem (punktem)" },
            { "ZCZWSP2TIRwPKTzmczciwsppodwtirwpktartykuempunktem", "Z/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt artykułem (punktem)" },
            { "ZCZWSP2TIRwTIRzmczciwsppodwtirwtirartykuempunktem", "Z/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. artykułem (punktem)" },
            { "ZCZWSP2TIRzmczciwsplnejpodwtirartykuempunktem", "Z/CZ_WSP_2TIR – zm. części wspólnej podw. tir. artykułem (punktem)" },
            { "ZCZWSPLITODNONIKAzmczciwsplitodnonikaartykuempunktem", "Z/CZ_WSP_LIT_ODNOŚNIKA – zm. części wsp. lit odnośnika artykułem (punktem)" },
            { "ZCZWSPLITwPKTODNONIKAzmczciwsplitwpktodnonikaartykuempunktem", "Z/CZ_WSP_LIT_w_PKT_ODNOŚNIKA – zm. części wsp. lit. w pkt odnośnika artykułem (punktem)" },
            { "ZCZWSPLITwPKTwODNONIKUzmczciwsplitwpktwzmienianymodnonikuartykuempunktem", "Z/CZ_WSP_LIT_w_PKT_w_ODNOŚNIKU – zm. części wsp. lit. w pkt w zmienianym odnośniku artykułem (punktem)" },
            { "ZCZWSPLITwPKTzmczciwsplitwpktartykuempunktem", "Z/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt artykułem (punktem)" },
            { "ZCZWSPLITzmczciwsplitartykuempunktem", "Z/CZ_WSP_LIT – zm. części wsp. lit. artykułem (punktem)" },
            { "ZCZWSPPKTODNONIKAzmczciwsppktodnonikaartykuempunktem", "Z/CZ_WSP_PKT_ODNOŚNIKA – zm. części wsp. pkt odnośnika artykułem (punktem)" },
            { "ZCZWSPPKTwODNONIKUzmczciwsppktwzmienianymodnonikuartykuempunktem", "Z/CZ_WSP_PKT_w_ODNOŚNIKU – zm. części wsp. pkt w zmienianym odnośniku artykułem (punktem)" },
            { "ZCZWSPPKTzmczciwsppktartykuempunktem", "Z/CZ_WSP_PKT – zm. części wsp. pkt artykułem (punktem)" },
            { "ZCZWSPTIRwLITzmczciwsptirwlitartykuempunktem", "Z/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. artykułem (punktem)" },
            { "ZCZWSPTIRwPKTzmczciwsptirwpktartykuempunktem", "Z/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt artykułem (punktem)" },
            { "ZCZWSPTIRzmczciwsptirartykuempunktem", "Z/CZ_WSP_TIR – zm. części wsp. tir. artykułem (punktem)" },
            { "ZDANIENASTNOWYWIERSZODNONIKAnpzddrugienowywiersz", "ZDANIE_NAST_NOWY_WIERSZ_ODNOŚNIKA – np. zd. drugie (nowy wiersz)" },
            { "ZDANIENASTNOWYWIERSZnpzddrugienowywierszwust", "ZDANIE_NAST_NOWY_WIERSZ – np. zd. drugie (nowy wiersz) w ust." },
            { "ZFRAGzmfragmentunpzdaniaartykuempunktem", "Z/FRAG – zm. fragmentu (np. zdania) artykułem (punktem)" },
            { "ZLEGWMATFIZCHEMzmlegendywzorumatfizlubchemartykuempunktem", "Z/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) artykułem (punktem)" },
            { "ZLIT2TIRwLITzmpodwtirwlitliter", "Z_LIT/2TIR_w_LIT – zm. podw. tir. w lit. literą" },
            { "ZLIT2TIRwPKTzmpodwtirwpktliter", "Z_LIT/2TIR_w_PKT – zm. podw. tir. w pkt literą" },
            { "ZLIT2TIRwTIRzmpodwtirwtirliter", "Z_LIT/2TIR_w_TIR – zm. podw. tir. w tir. literą" },
            { "ZLIT2TIRzmpodwtirliter", "Z_LIT/2TIR – zm. podw. tir. literą" },
            { "ZLITARTzmartliter", "Z_LIT/ART(§) – zm. art. (§) literą" },
            { "ZLITCYTzmcytatunpprzysigiliter", "Z_LIT/CYT – zm. cytatu np. przysięgi literą" },
            { "ZLITCZWSP2TIRwLITzmczciwsppodwtirwlitliter", "Z_LIT/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. literą" },
            { "ZLITCZWSP2TIRwPKTzmczciwsppodwtirwpktliter", "Z_LIT/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt literą" },
            { "ZLITCZWSP2TIRwTIRzmczciwsppodwtirwtirliter", "Z_LIT/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. literą" },
            { "ZLITCZWSP2TIRzmczciwsppodwtirliter", "Z_LIT/CZ_WSP_2TIR – zm. części wsp. podw. tir. literą" },
            { "ZLITCZWSPLITwPKTzmczciwsplitwpktliter", "Z_LIT/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt literą" },
            { "ZLITCZWSPLITzmczciwsplitliter", "Z_LIT/CZ_WSP_LIT – zm. części wsp. lit. literą" },
            { "ZLITCZWSPPKTzmczciwsppktliter", "Z_LIT/CZ_WSP_PKT – zm. części wsp. pkt literą" },
            { "ZLITCZWSPTIRwLITzmczciwsptirwlitliter", "Z_LIT/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. literą" },
            { "ZLITCZWSPTIRwPKTzmczciwsptirwpktliter", "Z_LIT/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt literą" },
            { "ZLITCZWSPTIRzmczciwsptirliter", "Z_LIT/CZ_WSP_TIR – zm. części wsp. tir. literą" },
            { "ZLITFRAGzmlitfragmentunpzdanialiter", "Z_LIT/FRAG – zm. lit. fragmentu (np. zdania) literą" },
            { "ZLITKSIGIzmozniprzedmksigiliter", "Z_LIT/KSIĘGI – zm. ozn. i przedm. księgi literą" },
            { "ZLITLEGWMATFIZCHEMzmlegendywzorumatfizlubchemliter", "Z_LIT/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) literą" },
            { "ZLITLITwPKTzmlitwpktliter", "Z_LIT/LIT_w_PKT – zm. lit. w pkt literą" },
            { "ZLITLITzmlitliter", "Z_LIT/LIT – zm. lit. literą" },
            { "ZLITODNONIKAzmlitodnonikaartykuempunktem", "Z/LIT_ODNOŚNIKA – zm. lit. odnośnika artykułem (punktem)" },
            { "ZLITPKTzmpktliter", "Z_LIT/PKT – zm. pkt literą" },
            { "ZLITROZDZODDZOZNzmoznrozdzoddzliter", "Z_LIT/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) literą" },
            { "ZLITROZDZODDZPRZEDMzmprzedmrozdzoddzliter", "Z_LIT/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) literą" },
            { "ZLITSKARNzmsankcjikarnejliter", "Z_LIT/S_KARN – zm. sankcji karnej literą" },
            { "ZLITTIRwLITzmtirwlitliter", "Z_LIT/TIR_w_LIT – zm. tir. w lit. literą" },
            { "ZLITTIRwPKTzmtirwpktliter", "Z_LIT/TIR_w_PKT – zm. tir. w pkt literą" },
            { "ZLITTIRzmtirliter", "Z_LIT/TIR – zm. tir. literą" },
            { "ZLITTYTDZOZNzmozntytuudziauliter", "Z_LIT/TYT(DZ)_OZN – zm. ozn. tytułu (działu) literą" },
            { "ZLITTYTDZPRZEDMzmprzedmtytuudziauliter", "Z_LIT/TYT(DZ)_PRZEDM – zm. przedm. tytułu (działu) literą" },
            { "ZLITUSTzmustliter", "Z_LIT/UST(§) – zm. ust. (§) literą" },
            { "ZLITWMATFIZCHEMzmwzorumatfizlubchemliter", "Z_LIT/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) literą" },
            { "ZLITwPKTODNONIKAzmlitwpktodnonikaartykuempunktem", "Z/LIT_w_PKT_ODNOŚNIKA – zm. lit. w pkt odnośnika artykułem (punktem)" },
            { "ZLITwPKTwODNONIKUzmlitwpktwzmienianymodnonikuartykuempunktem", "Z/LIT_w_PKT_w_ODNOŚNIKU – zm. lit. w pkt w zmienianym odnośniku artykułem (punktem)" },
            { "ZLITwPKTzmlitwpktartykuempunktem", "Z/LIT_w_PKT – zm. lit. w pkt artykułem (punktem)" },
            { "ZLITzmlitartykuempunktem", "Z/LIT – zm. lit. artykułem (punktem)" },
            { "ZNIEARTTEKSTzmtekstunieartykuowanego", "Z/NIEART_TEKST – zm. tekstu nieartykułowanego" },
            { "ZODNONIKAzmtekstuodnonikaartykuempunktem", "Z/ODNOŚNIKA – zm. tekstu odnośnika artykułem (punktem)" },
            { "ZPKTODNONIKAzmpktodnonikaartykuempunktem", "Z/PKT_ODNOŚNIKA – zm. pkt odnośnika artykułem (punktem)" },
            { "ZPKTwODNONIKUzmpktwzmienianymodnonikuartykuempunktem", "Z/PKT_w_ODNOŚNIKU – zm. pkt w zmienianym odnośniku artykułem (punktem)" },
            { "ZPKTzmpktartykuempunktem", "Z/PKT – zm. pkt artykułem (punktem)" },
            { "ZROZDZODDZOZNzmoznrozdzoddzartykuempunktem", "Z/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) artykułem (punktem)" },
            { "ZROZDZODDZPRZEDMzmprzedmrozdzoddzartykuempunktem", "Z/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) artykułem (punktem)" },
            { "ZSKARNzmsankcjikarnejwszczeglnociwKodeksiekarnym", "Z/S_KARN – zm. sankcji karnej w szczególności w Kodeksie karnym" },
            { "ZTIR2TIRwLITzmpodwtirwlittiret", "Z_TIR/2TIR_w_LIT – zm. podw. tir. w lit. tiret" },
            { "ZTIR2TIRwPKTzmpodwtirwpkttiret", "Z_TIR/2TIR_w_PKT – zm. podw. tir. w pkt tiret" },
            { "ZTIR2TIRwTIRzmpodwtirwtirtiret", "Z_TIR/2TIR_w_TIR – zm. podw. tir. w tir. tiret" },
            { "ZTIR2TIRzmpodwtirtiret", "Z_TIR/2TIR – zm. podw. tir. tiret" },
            { "ZTIRARTzmarttiret", "Z_TIR/ART(§) – zm. art. (§) tiret" },
            { "ZTIRCYTzmcytatunpprzysigitiret", "Z_TIR/CYT – zm. cytatu np. przysięgi tiret" },
            { "ZTIRCZWSP2TIRwLITzmczciwsppodwtirwlittiret", "Z_TIR/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. tiret" },
            { "ZTIRCZWSP2TIRwPKTzmczciwsppodwtirwpkttiret", "Z_TIR/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt tiret" },
            { "ZTIRCZWSP2TIRwTIRzmczciwsppodwtirwtirtiret", "Z_TIR/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. tiret" },
            { "ZTIRCZWSP2TIRzmczciwsppodwtirtiret", "Z_TIR/CZ_WSP_2TIR – zm. części wsp. podw. tir. tiret" },
            { "ZTIRCZWSPLITwPKTzmczciwsplitwpkttiret", "Z_TIR/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt tiret" },
            { "ZTIRCZWSPLITzmczciwsplittiret", "Z_TIR/CZ_WSP_LIT – zm. części wsp. lit. tiret" },
            { "ZTIRCZWSPPKTzmczciwsppkttiret", "Z_TIR/CZ_WSP_PKT – zm. części wsp. pkt tiret" },
            { "ZTIRCZWSPTIRwLITzmczciwsptirwlittiret", "Z_TIR/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. tiret" },
            { "ZTIRCZWSPTIRwPKTzmczciwsptirtiret", "Z_TIR/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. tiret" },
            { "ZTIRCZWSPTIRzmczciwsptirtiret", "Z_TIR/CZ_WSP_TIR – zm. części wsp. tir. tiret" },
            { "ZTIRDZOZNzmozndziautiret", "Z_TIR/DZ_OZN – zm. ozn. działu tiret" },
            { "ZTIRDZPRZEDMzmprzedmdziautiret", "Z_TIR/DZ_PRZEDM – zm. przedm. działu tiret" },
            { "ZTIRFRAGMzmnpwprdowyliczeniatiret", "Z_TIR/FRAGM – zm. np. wpr. do wyliczenia tiret" },
            { "ZTIRLEGWMATFIZCHEMzmlegendywzorumatfizlubchemtiret", "Z_TIR/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) tiret" },
            { "ZTIRLITwPKTzmlitwpkttiret", "Z_TIR/LIT_w_PKT – zm. lit. w pkt tiret" },
            { "ZTIRLITzmlittiret", "Z_TIR/LIT – zm. lit. tiret" },
            { "ZTIRPKTzmpkttiret", "Z_TIR/PKT – zm. pkt tiret" },
            { "ZTIRROZDZODDZOZNzmoznrozdzoddztiret", "Z_TIR/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) tiret" },
            { "ZTIRROZDZODDZPRZEDMzmprzedmrozdzoddztiret", "Z_TIR/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) tiret" },
            { "ZTIRSKARNzmsankcjikarnejtiret", "Z_TIR/S_KARN – zm. sankcji karnej tiret" },
            { "ZTIRTIRwLITzmtirwlittiret", "Z_TIR/TIR_w_LIT – zm. tir. w lit. tiret" },
            { "ZTIRTIRwPKTzmtirwpkttiret", "Z_TIR/TIR_w_PKT – zm. tir. w pkt tiret" },
            { "ZTIRTIRzmtirtiret", "Z_TIR/TIR – zm. tir. tiret" },
            { "ZTIRUSTzmusttiret", "Z_TIR/UST(§) – zm. ust. (§) tiret" },
            { "ZTIRWMATFIZCHEMzmwzorumatfizlubchemtiret", "Z_TIR/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) tiret" },
            { "ZTIRwLITzmtirwlitartykuempunktem", "Z/TIR_w_LIT – zm. tir. w lit. artykułem (punktem)" },
            { "ZTIRwPKTzmtirwpktartykuempunktem", "Z/TIR_w_PKT – zm. tir. w pkt artykułem (punktem)" },
            { "ZTIRzmtirartykuempunktem", "Z/TIR – zm. tir. artykułem (punktem)" },
            { "ZTYTDZOZNzmozntytuudziauartykuempunktem", "Z/TYT(DZ)_OZN – zm. ozn. tytułu (działu) artykułem (punktem)" },
            { "ZTYTDZPRZEDMzmprzedmtytuulubdziauartykuempunktem", "Z/TYT(DZ)_PRZEDM – zm. przedm. tytułu lub działu artykułem (punktem)" },
            { "ZUSTzmustartykuempunktem", "Z/UST(§) – zm. ust. (§) artykułem (punktem)" },
            { "ZWMATFIZCHEMzmwzorumatfizlubchemartykuempunktem", "Z/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) artykułem (punktem)" },
            { "ZZ2TIRwLITzmianazmpodwtirwlit", "ZZ/2TIR_w_LIT – zmiana zm. podw. tir. w lit." },
            { "ZZ2TIRwPKTzmianazmpodwtirwpkt", "ZZ/2TIR_w_PKT – zmiana zm. podw. tir. w pkt" },
            { "ZZ2TIRwTIRzmianazmpodwtirwtir", "ZZ/2TIR_w_TIR – zmiana zm. podw. tir. w tir." },
            { "ZZ2TIRzmianazmpodwtir", "ZZ/2TIR – zmiana zm. podw. tir." },
            { "ZZARTzmianazmart", "ZZ/ART(§) – zmiana zm. art. (§)" },
            { "ZZCYTzmianazmcytatunpprzysigi", "ZZ/CYT – zmiana zm. cytatu np. przysięgi" },
            { "ZZCZCIKSIGIzmianazmozniprzedmczciksigiartykuempunktem", "ZZ/CZĘŚCI(KSIĘGI) – zmiana zm. ozn. i przedm. części (księgi) artykułem (punktem)" },
            { "ZZCZWSP2TIRwLITzmianazmczciwsppodwtirwlit", "ZZ/CZ_WSP_2TIR_w_LIT – zmiana zm. części wsp. podw. tir. w lit." },
            { "ZZCZWSP2TIRwPKTzmianazmczciwsppodwtirwpkt", "ZZ/CZ_WSP_2TIR_w_PKT – zmiana zm. części wsp. podw. tir. w pkt" },
            { "ZZCZWSP2TIRwTIRzmianazmczciwsppodwtirwtir", "ZZ/CZ_WSP_2TIR_w_TIR – zmiana zm. części wsp. podw. tir. w tir." },
            { "ZZCZWSP2TIRzmianazmczciwsppodwtir", "ZZ/CZ_WSP_2TIR – zmiana zm. części wsp. podw. tir." },
            { "ZZCZWSPLITwPKTzmianazmczciwsplitwpkt", "ZZ/CZ_WSP_LIT_w_PKT – zmiana zm. części wsp. lit. w pkt" },
            { "ZZCZWSPLITzmianazmczciwsplit", "ZZ/CZ_WSP_LIT – zmiana. zm. części wsp. lit." },
            { "ZZCZWSPPKTzmianazmczciwsppkt", "ZZ/CZ_WSP_PKT – zmiana. zm. części wsp. pkt" },
            { "ZZCZWSPTIRwLITzmianazmczciwsptirwlit", "ZZ/CZ_WSP_TIR_w_LIT – zmiana zm. części wsp. tir. w lit." },
            { "ZZCZWSPTIRwPKTzmianazmczciwsptirwpkt", "ZZ/CZ_WSP_TIR_w_PKT – zmiana zm. części wsp. tir. w pkt" },
            { "ZZCZWSPTIRzmianazmczciwsptir", "ZZ/CZ_WSP_TIR – zmiana. zm. części wsp. tir." },
            { "ZZFRAGzmianazmfragmentunpzdania", "ZZ/FRAG – zmiana zm. fragmentu (np. zdania)" },
            { "ZZLEGWMATFIZCHEMzmlegendywzorumatfizlubchem", "ZZ/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.)" },
            { "ZZLITwPKTzmianazmlitwpkt", "ZZ/LIT_w_PKT – zmiana zm. lit. w pkt" },
            { "ZZLITzmianazmlit", "ZZ/LIT – zmiana zm. lit." },
            { "ZZPKTzmianazmpkt", "ZZ/PKT – zmiana zm. pkt" },
            { "ZZROZDZODDZOZNzmianazmoznrozdzoddzartykuempunktem", "ZZ/ROZDZ(ODDZ)_OZN – zmiana zm. ozn. rozdz. (oddz.) artykułem (punktem)" },
            { "ZZROZDZODDZPRZEDMzmianazmprzedmrozdzoddzartykuempunktem", "ZZ/ROZDZ(ODDZ)_PRZEDM – zmiana zm. przedm. rozdz. (oddz.) artykułem (punktem)" },
            { "ZZSKARNzmianazmsankcjikarnej", "ZZ/S_KARN – zmiana zm. sankcji karnej" },
            { "ZZTIRwLITzmianazmtirwlit", "ZZ/TIR_w_LIT – zmiana zm. tir. w lit." },
            { "ZZTIRwPKTzmianazmtirwpkt", "ZZ/TIR_w_PKT – zmiana zm. tir. w pkt" },
            { "ZZTIRzmianazmtir", "ZZ/TIR – zmiana zm. tir." },
            { "ZZTYTDZOZNzmianazmozntytuudziauartykuempunktem", "ZZ/TYT(DZ)_OZN – zmiana zm. ozn. tytułu (działu) artykułem (punktem)" },
            { "ZZTYTDZPRZEDMzmianazmprzedmtytuulubdziauartykuempunktem", "ZZ/TYT(DZ)_PRZEDM – zmiana zm. przedm. tytułu lub działu artykułem (punktem)" },
            { "ZZUSTzmianazmust", "ZZ/UST(§) – zmiana zm. ust. (§)" },
            { "ZZWMATFIZCHEMzmwzorumatfizlubchem", "ZZ/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.)" }
        };

		/// <summary>
		/// Statyczna mapa metadanych styli nowelizacyjnych.
		/// Kazdy styl Z/, Z_LIT/, Z_TIR/, Z_2TIR/, ZZ/ ma tu pre-obliczone
		/// <see cref="AmendmentStyleInfo"/> — bez zadnego parsowania w runtime.
		/// </summary>
		public static readonly IReadOnlyDictionary<string, AmendmentStyleInfo> AmendmentStyleInfoMap =
			new Dictionary<string, AmendmentStyleInfo>(StringComparer.OrdinalIgnoreCase)
		{
			{ "Z2TIR2TIRzmpodwtirpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.DoubleTiret, ShortCode = "Z_2TIR/2TIR", DisplayName = "Z_2TIR/2TIR – zm. podw. tir. podwójnym tiret" } },
			{ "Z2TIR2TIRwLITzmpodwtirwlitpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_2TIR/2TIR_w_LIT", DisplayName = "Z_2TIR/2TIR_w_LIT – zm. podw. tir. w lit. podwójnym tiret" } },
			{ "Z2TIR2TIRwPKTzmpodwtirwpktpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_2TIR/2TIR_w_PKT", DisplayName = "Z_2TIR/2TIR_w_PKT – zm. podw. tir. w pkt podwójnym tiret" } },
			{ "Z2TIR2TIRwTIRzmpodwtirwtirpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "Z_2TIR/2TIR_w_TIR", DisplayName = "Z_2TIR/2TIR_w_TIR – zm. podw. tir. w tir. podwójnym tiret" } },
			{ "Z2TIRARTzmartpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Article, ShortCode = "Z_2TIR/ART(§)", DisplayName = "Z_2TIR/ART(§) – zm. art. (§) podwójnym tiret" } },
			{ "Z2TIRCYTzmcytatunpprzysigipodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Citation, ShortCode = "Z_2TIR/CYT", DisplayName = "Z_2TIR/CYT – zm. cytatu np. przysięgi podwójnym tiret" } },
			{ "Z2TIRCZWSP2TIRzmczciwsppodwtirpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ShortCode = "Z_2TIR/CZ_WSP_2TIR", DisplayName = "Z_2TIR/CZ_WSP_2TIR – zm. części wsp. podw. tir. podwójnym tiret" } },
			{ "Z2TIRCZWSP2TIRwLITzmczciwsppodwtirwlitpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_2TIR/CZ_WSP_2TIR_w_LIT", DisplayName = "Z_2TIR/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. podwójnym tiret" } },
			{ "Z2TIRCZWSP2TIRwPKTzmczciwsppodwtirwpktpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_2TIR/CZ_WSP_2TIR_w_PKT", DisplayName = "Z_2TIR/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt podwójnym tiret" } },
			{ "Z2TIRCZWSP2TIRwTIRzmczciwsppodwtirwtiretpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "Z_2TIR/CZ_WSP_2TIR_w_TIR", DisplayName = "Z_2TIR/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tiret podwójnym tiret" } },
			{ "Z2TIRCZWSPLITzmczciwsplitpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ShortCode = "Z_2TIR/CZ_WSP_LIT", DisplayName = "Z_2TIR/CZ_WSP_LIT – zm. części wsp. lit. podwójnym tiret" } },
			{ "Z2TIRCZWSPLITwPKTzmczciwsplitwpktpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_2TIR/CZ_WSP_LIT_w_PKT", DisplayName = "Z_2TIR/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt podwójnym tiret" } },
			{ "Z2TIRCZWSPPKTzmczciwsppktpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Point, ShortCode = "Z_2TIR/CZ_WSP_PKT", DisplayName = "Z_2TIR/CZ_WSP_PKT – zm. części wsp. pkt podwójnym tiret" } },
			{ "Z2TIRCZWSPTIRzmczciwsptirpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ShortCode = "Z_2TIR/CZ_WSP_TIR", DisplayName = "Z_2TIR/CZ_WSP_TIR – zm. części wsp. tir. podwójnym tiret" } },
			{ "Z2TIRCZWSPTIRwLITzmczciwsptirwlitpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_2TIR/CZ_WSP_TIR_w_LIT", DisplayName = "Z_2TIR/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. podwójnym tiret" } },
			{ "Z2TIRCZWSPTIRwPKTzmczciwsptirwpktpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_2TIR/CZ_WSP_TIR_w_PKT", DisplayName = "Z_2TIR/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt podwójnym tiret" } },
			{ "Z2TIRFRAGMzmnpwprdowyliczeniapodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Fragment, ShortCode = "Z_2TIR/FRAGM", DisplayName = "Z_2TIR/FRAGM – zm. np. wpr. do wyliczenia podwójnym tiret" } },
			{ "Z2TIRLEGWMATFIZCHEMzmlegendywzorumatfizlubchempodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.FormulaLegend, ShortCode = "Z_2TIR/LEG_W_MAT(FIZ|CHEM)", DisplayName = "Z_2TIR/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) podwójnym tiret" } },
			{ "Z2TIRLITzmlitpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Letter, ShortCode = "Z_2TIR/LIT", DisplayName = "Z_2TIR/LIT – zm. lit. podwójnym tiret" } },
			{ "Z2TIRLITwPKTzmlitwpktpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_2TIR/LIT_w_PKT", DisplayName = "Z_2TIR/LIT_w_PKT – zm. lit. w pkt podwójnym tiret" } },
			{ "Z2TIRPKTzmpktpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Point, ShortCode = "Z_2TIR/PKT", DisplayName = "Z_2TIR/PKT – zm. pkt podwójnym tiret" } },
			{ "Z2TIRROZDZODDZOZNzmoznrozdzoddzpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_2TIR/ROZDZ(ODDZ)_OZN", DisplayName = "Z_2TIR/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) podwójnym tiret" } },
			{ "Z2TIRROZDZODDZPRZEDMzmprzedmrozdzoddzpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_2TIR/ROZDZ(ODDZ)_PRZEDM", DisplayName = "Z_2TIR/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) podwójnym tiret" } },
			{ "Z2TIRSKARNzmianasankcjikarnejpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.PenalSanction, ShortCode = "Z_2TIR/S_KARN", DisplayName = "Z_2TIR/S_KARN – zmiana sankcji karnej podwójnym tiret" } },
			{ "Z2TIRTIRzmtirpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Tiret, ShortCode = "Z_2TIR/TIR", DisplayName = "Z_2TIR/TIR – zm. tir. podwójnym tiret" } },
			{ "Z2TIRTIRwLITzmtirwlitpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_2TIR/TIR_w_LIT", DisplayName = "Z_2TIR/TIR_w_LIT – zm. tir. w lit. podwójnym tiret" } },
			{ "Z2TIRTIRwPKTzmtirwpktpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_2TIR/TIR_w_PKT", DisplayName = "Z_2TIR/TIR_w_PKT – zm. tir. w pkt podwójnym tiret" } },
			{ "Z2TIRUSTzmustpodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Paragraph, ShortCode = "Z_2TIR/UST(§)", DisplayName = "Z_2TIR/UST(§) – zm. ust. (§) podwójnym tiret" } },
			{ "Z2TIRWMATFIZCHEMzmwzorumatfizlubchempodwjnymtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.DoubleTiret, TargetKind = AmendmentTargetKind.Formula, ShortCode = "Z_2TIR/W_MAT(FIZ|CHEM)", DisplayName = "Z_2TIR/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) podwójnym tiret" } },
			{ "ZLIT2TIRzmpodwtirliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.DoubleTiret, ShortCode = "Z_LIT/2TIR", DisplayName = "Z_LIT/2TIR – zm. podw. tir. literą" } },
			{ "ZLIT2TIRwLITzmpodwtirwlitliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_LIT/2TIR_w_LIT", DisplayName = "Z_LIT/2TIR_w_LIT – zm. podw. tir. w lit. literą" } },
			{ "ZLIT2TIRwPKTzmpodwtirwpktliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_LIT/2TIR_w_PKT", DisplayName = "Z_LIT/2TIR_w_PKT – zm. podw. tir. w pkt literą" } },
			{ "ZLIT2TIRwTIRzmpodwtirwtirliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "Z_LIT/2TIR_w_TIR", DisplayName = "Z_LIT/2TIR_w_TIR – zm. podw. tir. w tir. literą" } },
			{ "ZLITARTzmartliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Article, ShortCode = "Z_LIT/ART(§)", DisplayName = "Z_LIT/ART(§) – zm. art. (§) literą" } },
			{ "ZLITCYTzmcytatunpprzysigiliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Citation, ShortCode = "Z_LIT/CYT", DisplayName = "Z_LIT/CYT – zm. cytatu np. przysięgi literą" } },
			{ "ZLITCZWSP2TIRzmczciwsppodwtirliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ShortCode = "Z_LIT/CZ_WSP_2TIR", DisplayName = "Z_LIT/CZ_WSP_2TIR – zm. części wsp. podw. tir. literą" } },
			{ "ZLITCZWSP2TIRwLITzmczciwsppodwtirwlitliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_LIT/CZ_WSP_2TIR_w_LIT", DisplayName = "Z_LIT/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. literą" } },
			{ "ZLITCZWSP2TIRwPKTzmczciwsppodwtirwpktliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_LIT/CZ_WSP_2TIR_w_PKT", DisplayName = "Z_LIT/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt literą" } },
			{ "ZLITCZWSP2TIRwTIRzmczciwsppodwtirwtirliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "Z_LIT/CZ_WSP_2TIR_w_TIR", DisplayName = "Z_LIT/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. literą" } },
			{ "ZLITCZWSPLITzmczciwsplitliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ShortCode = "Z_LIT/CZ_WSP_LIT", DisplayName = "Z_LIT/CZ_WSP_LIT – zm. części wsp. lit. literą" } },
			{ "ZLITCZWSPLITwPKTzmczciwsplitwpktliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_LIT/CZ_WSP_LIT_w_PKT", DisplayName = "Z_LIT/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt literą" } },
			{ "ZLITCZWSPPKTzmczciwsppktliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Point, ShortCode = "Z_LIT/CZ_WSP_PKT", DisplayName = "Z_LIT/CZ_WSP_PKT – zm. części wsp. pkt literą" } },
			{ "ZLITCZWSPTIRzmczciwsptirliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ShortCode = "Z_LIT/CZ_WSP_TIR", DisplayName = "Z_LIT/CZ_WSP_TIR – zm. części wsp. tir. literą" } },
			{ "ZLITCZWSPTIRwLITzmczciwsptirwlitliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_LIT/CZ_WSP_TIR_w_LIT", DisplayName = "Z_LIT/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. literą" } },
			{ "ZLITCZWSPTIRwPKTzmczciwsptirwpktliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_LIT/CZ_WSP_TIR_w_PKT", DisplayName = "Z_LIT/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt literą" } },
			{ "ZLITFRAGzmlitfragmentunpzdanialiter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Fragment, ShortCode = "Z_LIT/FRAG", DisplayName = "Z_LIT/FRAG – zm. lit. fragmentu (np. zdania) literą" } },
			{ "ZLITKSIGIzmozniprzedmksigiliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_LIT/KSIĘGI", DisplayName = "Z_LIT/KSIĘGI – zm. ozn. i przedm. księgi literą" } },
			{ "ZLITLEGWMATFIZCHEMzmlegendywzorumatfizlubchemliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.FormulaLegend, ShortCode = "Z_LIT/LEG_W_MAT(FIZ|CHEM)", DisplayName = "Z_LIT/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) literą" } },
			{ "ZLITLITzmlitliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Letter, ShortCode = "Z_LIT/LIT", DisplayName = "Z_LIT/LIT – zm. lit. literą" } },
			{ "ZLITLITwPKTzmlitwpktliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_LIT/LIT_w_PKT", DisplayName = "Z_LIT/LIT_w_PKT – zm. lit. w pkt literą" } },
			{ "ZLITPKTzmpktliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Point, ShortCode = "Z_LIT/PKT", DisplayName = "Z_LIT/PKT – zm. pkt literą" } },
			{ "ZLITROZDZODDZOZNzmoznrozdzoddzliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_LIT/ROZDZ(ODDZ)_OZN", DisplayName = "Z_LIT/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) literą" } },
			{ "ZLITROZDZODDZPRZEDMzmprzedmrozdzoddzliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_LIT/ROZDZ(ODDZ)_PRZEDM", DisplayName = "Z_LIT/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) literą" } },
			{ "ZLITSKARNzmsankcjikarnejliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.PenalSanction, ShortCode = "Z_LIT/S_KARN", DisplayName = "Z_LIT/S_KARN – zm. sankcji karnej literą" } },
			{ "ZLITTIRzmtirliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Tiret, ShortCode = "Z_LIT/TIR", DisplayName = "Z_LIT/TIR – zm. tir. literą" } },
			{ "ZLITTIRwLITzmtirwlitliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_LIT/TIR_w_LIT", DisplayName = "Z_LIT/TIR_w_LIT – zm. tir. w lit. literą" } },
			{ "ZLITTIRwPKTzmtirwpktliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_LIT/TIR_w_PKT", DisplayName = "Z_LIT/TIR_w_PKT – zm. tir. w pkt literą" } },
			{ "ZLITTYTDZOZNzmozntytuudziauliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_LIT/TYT(DZ)_OZN", DisplayName = "Z_LIT/TYT(DZ)_OZN – zm. ozn. tytułu (działu) literą" } },
			{ "ZLITTYTDZPRZEDMzmprzedmtytuudziauliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_LIT/TYT(DZ)_PRZEDM", DisplayName = "Z_LIT/TYT(DZ)_PRZEDM – zm. przedm. tytułu (działu) literą" } },
			{ "ZLITUSTzmustliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Paragraph, ShortCode = "Z_LIT/UST(§)", DisplayName = "Z_LIT/UST(§) – zm. ust. (§) literą" } },
			{ "ZLITWMATFIZCHEMzmwzorumatfizlubchemliter", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Letter, TargetKind = AmendmentTargetKind.Formula, ShortCode = "Z_LIT/W_MAT(FIZ|CHEM)", DisplayName = "Z_LIT/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) literą" } },
			{ "ZTIR2TIRzmpodwtirtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.DoubleTiret, ShortCode = "Z_TIR/2TIR", DisplayName = "Z_TIR/2TIR – zm. podw. tir. tiret" } },
			{ "ZTIR2TIRwLITzmpodwtirwlittiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_TIR/2TIR_w_LIT", DisplayName = "Z_TIR/2TIR_w_LIT – zm. podw. tir. w lit. tiret" } },
			{ "ZTIR2TIRwPKTzmpodwtirwpkttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_TIR/2TIR_w_PKT", DisplayName = "Z_TIR/2TIR_w_PKT – zm. podw. tir. w pkt tiret" } },
			{ "ZTIR2TIRwTIRzmpodwtirwtirtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "Z_TIR/2TIR_w_TIR", DisplayName = "Z_TIR/2TIR_w_TIR – zm. podw. tir. w tir. tiret" } },
			{ "ZTIRARTzmarttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Article, ShortCode = "Z_TIR/ART(§)", DisplayName = "Z_TIR/ART(§) – zm. art. (§) tiret" } },
			{ "ZTIRCYTzmcytatunpprzysigitiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Citation, ShortCode = "Z_TIR/CYT", DisplayName = "Z_TIR/CYT – zm. cytatu np. przysięgi tiret" } },
			{ "ZTIRCZWSP2TIRzmczciwsppodwtirtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ShortCode = "Z_TIR/CZ_WSP_2TIR", DisplayName = "Z_TIR/CZ_WSP_2TIR – zm. części wsp. podw. tir. tiret" } },
			{ "ZTIRCZWSP2TIRwLITzmczciwsppodwtirwlittiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_TIR/CZ_WSP_2TIR_w_LIT", DisplayName = "Z_TIR/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. tiret" } },
			{ "ZTIRCZWSP2TIRwPKTzmczciwsppodwtirwpkttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_TIR/CZ_WSP_2TIR_w_PKT", DisplayName = "Z_TIR/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt tiret" } },
			{ "ZTIRCZWSP2TIRwTIRzmczciwsppodwtirwtirtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "Z_TIR/CZ_WSP_2TIR_w_TIR", DisplayName = "Z_TIR/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. tiret" } },
			{ "ZTIRCZWSPLITzmczciwsplittiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ShortCode = "Z_TIR/CZ_WSP_LIT", DisplayName = "Z_TIR/CZ_WSP_LIT – zm. części wsp. lit. tiret" } },
			{ "ZTIRCZWSPLITwPKTzmczciwsplitwpkttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_TIR/CZ_WSP_LIT_w_PKT", DisplayName = "Z_TIR/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt tiret" } },
			{ "ZTIRCZWSPPKTzmczciwsppkttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Point, ShortCode = "Z_TIR/CZ_WSP_PKT", DisplayName = "Z_TIR/CZ_WSP_PKT – zm. części wsp. pkt tiret" } },
			{ "ZTIRCZWSPTIRzmczciwsptirtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ShortCode = "Z_TIR/CZ_WSP_TIR", DisplayName = "Z_TIR/CZ_WSP_TIR – zm. części wsp. tir. tiret" } },
			{ "ZTIRCZWSPTIRwLITzmczciwsptirwlittiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_TIR/CZ_WSP_TIR_w_LIT", DisplayName = "Z_TIR/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. tiret" } },
			{ "ZTIRCZWSPTIRwPKTzmczciwsptirtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_TIR/CZ_WSP_TIR_w_PKT", DisplayName = "Z_TIR/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. tiret" } },
			{ "ZTIRDZOZNzmozndziautiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Unknown, ShortCode = "Z_TIR/DZ_OZN", DisplayName = "Z_TIR/DZ_OZN – zm. ozn. działu tiret" } },
			{ "ZTIRDZPRZEDMzmprzedmdziautiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Unknown, ShortCode = "Z_TIR/DZ_PRZEDM", DisplayName = "Z_TIR/DZ_PRZEDM – zm. przedm. działu tiret" } },
			{ "ZTIRFRAGMzmnpwprdowyliczeniatiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Fragment, ShortCode = "Z_TIR/FRAGM", DisplayName = "Z_TIR/FRAGM – zm. np. wpr. do wyliczenia tiret" } },
			{ "ZTIRLEGWMATFIZCHEMzmlegendywzorumatfizlubchemtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.FormulaLegend, ShortCode = "Z_TIR/LEG_W_MAT(FIZ|CHEM)", DisplayName = "Z_TIR/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) tiret" } },
			{ "ZTIRLITzmlittiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Letter, ShortCode = "Z_TIR/LIT", DisplayName = "Z_TIR/LIT – zm. lit. tiret" } },
			{ "ZTIRLITwPKTzmlitwpkttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_TIR/LIT_w_PKT", DisplayName = "Z_TIR/LIT_w_PKT – zm. lit. w pkt tiret" } },
			{ "ZTIRPKTzmpkttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Point, ShortCode = "Z_TIR/PKT", DisplayName = "Z_TIR/PKT – zm. pkt tiret" } },
			{ "ZTIRROZDZODDZOZNzmoznrozdzoddztiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_TIR/ROZDZ(ODDZ)_OZN", DisplayName = "Z_TIR/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) tiret" } },
			{ "ZTIRROZDZODDZPRZEDMzmprzedmrozdzoddztiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z_TIR/ROZDZ(ODDZ)_PRZEDM", DisplayName = "Z_TIR/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) tiret" } },
			{ "ZTIRSKARNzmsankcjikarnejtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.PenalSanction, ShortCode = "Z_TIR/S_KARN", DisplayName = "Z_TIR/S_KARN – zm. sankcji karnej tiret" } },
			{ "ZTIRTIRzmtirtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Tiret, ShortCode = "Z_TIR/TIR", DisplayName = "Z_TIR/TIR – zm. tir. tiret" } },
			{ "ZTIRTIRwLITzmtirwlittiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z_TIR/TIR_w_LIT", DisplayName = "Z_TIR/TIR_w_LIT – zm. tir. w lit. tiret" } },
			{ "ZTIRTIRwPKTzmtirwpkttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z_TIR/TIR_w_PKT", DisplayName = "Z_TIR/TIR_w_PKT – zm. tir. w pkt tiret" } },
			{ "ZTIRUSTzmusttiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Paragraph, ShortCode = "Z_TIR/UST(§)", DisplayName = "Z_TIR/UST(§) – zm. ust. (§) tiret" } },
			{ "ZTIRWMATFIZCHEMzmwzorumatfizlubchemtiret", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Tiret, TargetKind = AmendmentTargetKind.Formula, ShortCode = "Z_TIR/W_MAT(FIZ|CHEM)", DisplayName = "Z_TIR/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) tiret" } },
			{ "Z2TIRzmpodwtirartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.DoubleTiret, ShortCode = "Z/2TIR", DisplayName = "Z/2TIR – zm. podw. tir. artykułem (punktem)" } },
			{ "Z2TIRwLITzmpodwtirwlitartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z/2TIR_w_LIT", DisplayName = "Z/2TIR_w_LIT – zm. podw. tir. w lit. artykułem (punktem)" } },
			{ "Z2TIRwPKTzmpodwtirwpktartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z/2TIR_w_PKT", DisplayName = "Z/2TIR_w_PKT – zm. podw. tir. w pkt artykułem (punktem)" } },
			{ "Z2TIRwTIRzmpodwtirwtirartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "Z/2TIR_w_TIR", DisplayName = "Z/2TIR_w_TIR – zm. podw. tir. w tir. artykułem (punktem)" } },
			{ "ZARTzmartartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Article, ShortCode = "Z/ART(§)", DisplayName = "Z/ART(§) – zm. art. (§) artykułem (punktem)" } },
			{ "ZCYTzmcytatunpprzysigiartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Citation, ShortCode = "Z/CYT", DisplayName = "Z/CYT – zm. cytatu np. przysięgi artykułem (punktem)" } },
			{ "ZCZWSP2TIRzmczciwsplnejpodwtirartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ShortCode = "Z/CZ_WSP_2TIR", DisplayName = "Z/CZ_WSP_2TIR – zm. części wspólnej podw. tir. artykułem (punktem)" } },
			{ "ZCZWSP2TIRwLITzmczciwsppodwtirwlitartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z/CZ_WSP_2TIR_w_LIT", DisplayName = "Z/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. artykułem (punktem)" } },
			{ "ZCZWSP2TIRwPKTzmczciwsppodwtirwpktartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z/CZ_WSP_2TIR_w_PKT", DisplayName = "Z/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt artykułem (punktem)" } },
			{ "ZCZWSP2TIRwTIRzmczciwsppodwtirwtirartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "Z/CZ_WSP_2TIR_w_TIR", DisplayName = "Z/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. artykułem (punktem)" } },
			{ "ZCZWSPLITzmczciwsplitartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ShortCode = "Z/CZ_WSP_LIT", DisplayName = "Z/CZ_WSP_LIT – zm. części wsp. lit. artykułem (punktem)" } },
			{ "ZCZWSPLITODNONIKAzmczciwsplitodnonikaartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Footnote, ShortCode = "Z/CZ_WSP_LIT_ODNOŚNIKA", DisplayName = "Z/CZ_WSP_LIT_ODNOŚNIKA – zm. części wsp. lit odnośnika artykułem (punktem)" } },
			{ "ZCZWSPLITwPKTzmczciwsplitwpktartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z/CZ_WSP_LIT_w_PKT", DisplayName = "Z/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt artykułem (punktem)" } },
			{ "ZCZWSPLITwPKTODNONIKAzmczciwsplitwpktodnonikaartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Footnote, ShortCode = "Z/CZ_WSP_LIT_w_PKT_ODNOŚNIKA", DisplayName = "Z/CZ_WSP_LIT_w_PKT_ODNOŚNIKA – zm. części wsp. lit. w pkt odnośnika artykułem (punktem)" } },
			{ "ZCZWSPLITwPKTwODNONIKUzmczciwsplitwpktwzmienianymodnonikuartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Unknown, ShortCode = "Z/CZ_WSP_LIT_w_PKT_w_ODNOŚNIKU", DisplayName = "Z/CZ_WSP_LIT_w_PKT_w_ODNOŚNIKU – zm. części wsp. lit. w pkt w zmienianym odnośniku artykułem (punktem)" } },
			{ "ZCZWSPPKTzmczciwsppktartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Point, ShortCode = "Z/CZ_WSP_PKT", DisplayName = "Z/CZ_WSP_PKT – zm. części wsp. pkt artykułem (punktem)" } },
			{ "ZCZWSPPKTODNONIKAzmczciwsppktodnonikaartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Footnote, ShortCode = "Z/CZ_WSP_PKT_ODNOŚNIKA", DisplayName = "Z/CZ_WSP_PKT_ODNOŚNIKA – zm. części wsp. pkt odnośnika artykułem (punktem)" } },
			{ "ZCZWSPPKTwODNONIKUzmczciwsppktwzmienianymodnonikuartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Unknown, ShortCode = "Z/CZ_WSP_PKT_w_ODNOŚNIKU", DisplayName = "Z/CZ_WSP_PKT_w_ODNOŚNIKU – zm. części wsp. pkt w zmienianym odnośniku artykułem (punktem)" } },
			{ "ZCZWSPTIRzmczciwsptirartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ShortCode = "Z/CZ_WSP_TIR", DisplayName = "Z/CZ_WSP_TIR – zm. części wsp. tir. artykułem (punktem)" } },
			{ "ZCZWSPTIRwLITzmczciwsptirwlitartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z/CZ_WSP_TIR_w_LIT", DisplayName = "Z/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. artykułem (punktem)" } },
			{ "ZCZWSPTIRwPKTzmczciwsptirwpktartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z/CZ_WSP_TIR_w_PKT", DisplayName = "Z/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt artykułem (punktem)" } },
			{ "ZCZCIKSIGIzmozniprzedmczciksigiartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z/CZĘŚCI(KSIĘGI)", DisplayName = "Z/CZĘŚCI(KSIĘGI) – zm. ozn. i przedm. części (księgi) artykułem (punktem)" } },
			{ "ZFRAGzmfragmentunpzdaniaartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Fragment, ShortCode = "Z/FRAG", DisplayName = "Z/FRAG – zm. fragmentu (np. zdania) artykułem (punktem)" } },
			{ "ZLEGWMATFIZCHEMzmlegendywzorumatfizlubchemartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.FormulaLegend, ShortCode = "Z/LEG_W_MAT(FIZ|CHEM)", DisplayName = "Z/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) artykułem (punktem)" } },
			{ "ZLITzmlitartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Letter, ShortCode = "Z/LIT", DisplayName = "Z/LIT – zm. lit. artykułem (punktem)" } },
			{ "ZLITODNONIKAzmlitodnonikaartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Footnote, ShortCode = "Z/LIT_ODNOŚNIKA", DisplayName = "Z/LIT_ODNOŚNIKA – zm. lit. odnośnika artykułem (punktem)" } },
			{ "ZLITwPKTzmlitwpktartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z/LIT_w_PKT", DisplayName = "Z/LIT_w_PKT – zm. lit. w pkt artykułem (punktem)" } },
			{ "ZLITwPKTODNONIKAzmlitwpktodnonikaartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Footnote, ShortCode = "Z/LIT_w_PKT_ODNOŚNIKA", DisplayName = "Z/LIT_w_PKT_ODNOŚNIKA – zm. lit. w pkt odnośnika artykułem (punktem)" } },
			{ "ZLITwPKTwODNONIKUzmlitwpktwzmienianymodnonikuartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Unknown, ShortCode = "Z/LIT_w_PKT_w_ODNOŚNIKU", DisplayName = "Z/LIT_w_PKT_w_ODNOŚNIKU – zm. lit. w pkt w zmienianym odnośniku artykułem (punktem)" } },
			{ "ZNIEARTTEKSTzmtekstunieartykuowanego", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.NonArticleText, ShortCode = "Z/NIEART_TEKST", DisplayName = "Z/NIEART_TEKST – zm. tekstu nieartykułowanego" } },
			{ "ZODNONIKAzmtekstuodnonikaartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Footnote, ShortCode = "Z/ODNOŚNIKA", DisplayName = "Z/ODNOŚNIKA – zm. tekstu odnośnika artykułem (punktem)" } },
			{ "ZPKTzmpktartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Point, ShortCode = "Z/PKT", DisplayName = "Z/PKT – zm. pkt artykułem (punktem)" } },
			{ "ZPKTODNONIKAzmpktodnonikaartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Footnote, ShortCode = "Z/PKT_ODNOŚNIKA", DisplayName = "Z/PKT_ODNOŚNIKA – zm. pkt odnośnika artykułem (punktem)" } },
			{ "ZPKTwODNONIKUzmpktwzmienianymodnonikuartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Unknown, ShortCode = "Z/PKT_w_ODNOŚNIKU", DisplayName = "Z/PKT_w_ODNOŚNIKU – zm. pkt w zmienianym odnośniku artykułem (punktem)" } },
			{ "ZROZDZODDZOZNzmoznrozdzoddzartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z/ROZDZ(ODDZ)_OZN", DisplayName = "Z/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) artykułem (punktem)" } },
			{ "ZROZDZODDZPRZEDMzmprzedmrozdzoddzartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z/ROZDZ(ODDZ)_PRZEDM", DisplayName = "Z/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) artykułem (punktem)" } },
			{ "ZSKARNzmsankcjikarnejwszczeglnociwKodeksiekarnym", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.PenalSanction, ShortCode = "Z/S_KARN", DisplayName = "Z/S_KARN – zm. sankcji karnej w szczególności w Kodeksie karnym" } },
			{ "ZTIRzmtirartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Tiret, ShortCode = "Z/TIR", DisplayName = "Z/TIR – zm. tir. artykułem (punktem)" } },
			{ "ZTIRwLITzmtirwlitartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "Z/TIR_w_LIT", DisplayName = "Z/TIR_w_LIT – zm. tir. w lit. artykułem (punktem)" } },
			{ "ZTIRwPKTzmtirwpktartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "Z/TIR_w_PKT", DisplayName = "Z/TIR_w_PKT – zm. tir. w pkt artykułem (punktem)" } },
			{ "ZTYTDZOZNzmozntytuudziauartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z/TYT(DZ)_OZN", DisplayName = "Z/TYT(DZ)_OZN – zm. ozn. tytułu (działu) artykułem (punktem)" } },
			{ "ZTYTDZPRZEDMzmprzedmtytuulubdziauartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "Z/TYT(DZ)_PRZEDM", DisplayName = "Z/TYT(DZ)_PRZEDM – zm. przedm. tytułu lub działu artykułem (punktem)" } },
			{ "ZUSTzmustartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Paragraph, ShortCode = "Z/UST(§)", DisplayName = "Z/UST(§) – zm. ust. (§) artykułem (punktem)" } },
			{ "ZWMATFIZCHEMzmwzorumatfizlubchemartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.ArticleOrPoint, TargetKind = AmendmentTargetKind.Formula, ShortCode = "Z/W_MAT(FIZ|CHEM)", DisplayName = "Z/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) artykułem (punktem)" } },
			{ "ZZ2TIRzmianazmpodwtir", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.DoubleTiret, ShortCode = "ZZ/2TIR", DisplayName = "ZZ/2TIR – zmiana zm. podw. tir." } },
			{ "ZZ2TIRwLITzmianazmpodwtirwlit", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "ZZ/2TIR_w_LIT", DisplayName = "ZZ/2TIR_w_LIT – zmiana zm. podw. tir. w lit." } },
			{ "ZZ2TIRwPKTzmianazmpodwtirwpkt", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "ZZ/2TIR_w_PKT", DisplayName = "ZZ/2TIR_w_PKT – zmiana zm. podw. tir. w pkt" } },
			{ "ZZ2TIRwTIRzmianazmpodwtirwtir", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "ZZ/2TIR_w_TIR", DisplayName = "ZZ/2TIR_w_TIR – zmiana zm. podw. tir. w tir." } },
			{ "ZZARTzmianazmart", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Article, ShortCode = "ZZ/ART(§)", DisplayName = "ZZ/ART(§) – zmiana zm. art. (§)" } },
			{ "ZZCYTzmianazmcytatunpprzysigi", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Citation, ShortCode = "ZZ/CYT", DisplayName = "ZZ/CYT – zmiana zm. cytatu np. przysięgi" } },
			{ "ZZCZWSP2TIRzmianazmczciwsppodwtir", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ShortCode = "ZZ/CZ_WSP_2TIR", DisplayName = "ZZ/CZ_WSP_2TIR – zmiana zm. części wsp. podw. tir." } },
			{ "ZZCZWSP2TIRwLITzmianazmczciwsppodwtirwlit", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "ZZ/CZ_WSP_2TIR_w_LIT", DisplayName = "ZZ/CZ_WSP_2TIR_w_LIT – zmiana zm. części wsp. podw. tir. w lit." } },
			{ "ZZCZWSP2TIRwPKTzmianazmczciwsppodwtirwpkt", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "ZZ/CZ_WSP_2TIR_w_PKT", DisplayName = "ZZ/CZ_WSP_2TIR_w_PKT – zmiana zm. części wsp. podw. tir. w pkt" } },
			{ "ZZCZWSP2TIRwTIRzmianazmczciwsppodwtirwtir", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.DoubleTiret, ParentContext = AmendmentTargetKind.Tiret, ShortCode = "ZZ/CZ_WSP_2TIR_w_TIR", DisplayName = "ZZ/CZ_WSP_2TIR_w_TIR – zmiana zm. części wsp. podw. tir. w tir." } },
			{ "ZZCZWSPLITzmianazmczciwsplit", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ShortCode = "ZZ/CZ_WSP_LIT", DisplayName = "ZZ/CZ_WSP_LIT – zmiana. zm. części wsp. lit." } },
			{ "ZZCZWSPLITwPKTzmianazmczciwsplitwpkt", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "ZZ/CZ_WSP_LIT_w_PKT", DisplayName = "ZZ/CZ_WSP_LIT_w_PKT – zmiana zm. części wsp. lit. w pkt" } },
			{ "ZZCZWSPPKTzmianazmczciwsppkt", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Point, ShortCode = "ZZ/CZ_WSP_PKT", DisplayName = "ZZ/CZ_WSP_PKT – zmiana. zm. części wsp. pkt" } },
			{ "ZZCZWSPTIRzmianazmczciwsptir", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ShortCode = "ZZ/CZ_WSP_TIR", DisplayName = "ZZ/CZ_WSP_TIR – zmiana. zm. części wsp. tir." } },
			{ "ZZCZWSPTIRwLITzmianazmczciwsptirwlit", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "ZZ/CZ_WSP_TIR_w_LIT", DisplayName = "ZZ/CZ_WSP_TIR_w_LIT – zmiana zm. części wsp. tir. w lit." } },
			{ "ZZCZWSPTIRwPKTzmianazmczciwsptirwpkt", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.CommonPart, CommonPartOf = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "ZZ/CZ_WSP_TIR_w_PKT", DisplayName = "ZZ/CZ_WSP_TIR_w_PKT – zmiana zm. części wsp. tir. w pkt" } },
			{ "ZZCZCIKSIGIzmianazmozniprzedmczciksigiartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "ZZ/CZĘŚCI(KSIĘGI)", DisplayName = "ZZ/CZĘŚCI(KSIĘGI) – zmiana zm. ozn. i przedm. części (księgi) artykułem (punktem)" } },
			{ "ZZFRAGzmianazmfragmentunpzdania", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Fragment, ShortCode = "ZZ/FRAG", DisplayName = "ZZ/FRAG – zmiana zm. fragmentu (np. zdania)" } },
			{ "ZZLEGWMATFIZCHEMzmlegendywzorumatfizlubchem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.FormulaLegend, ShortCode = "ZZ/LEG_W_MAT(FIZ|CHEM)", DisplayName = "ZZ/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.)" } },
			{ "ZZLITzmianazmlit", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Letter, ShortCode = "ZZ/LIT", DisplayName = "ZZ/LIT – zmiana zm. lit." } },
			{ "ZZLITwPKTzmianazmlitwpkt", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Letter, ParentContext = AmendmentTargetKind.Point, ShortCode = "ZZ/LIT_w_PKT", DisplayName = "ZZ/LIT_w_PKT – zmiana zm. lit. w pkt" } },
			{ "ZZPKTzmianazmpkt", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Point, ShortCode = "ZZ/PKT", DisplayName = "ZZ/PKT – zmiana zm. pkt" } },
			{ "ZZROZDZODDZOZNzmianazmoznrozdzoddzartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "ZZ/ROZDZ(ODDZ)_OZN", DisplayName = "ZZ/ROZDZ(ODDZ)_OZN – zmiana zm. ozn. rozdz. (oddz.) artykułem (punktem)" } },
			{ "ZZROZDZODDZPRZEDMzmianazmprzedmrozdzoddzartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "ZZ/ROZDZ(ODDZ)_PRZEDM", DisplayName = "ZZ/ROZDZ(ODDZ)_PRZEDM – zmiana zm. przedm. rozdz. (oddz.) artykułem (punktem)" } },
			{ "ZZSKARNzmianazmsankcjikarnej", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.PenalSanction, ShortCode = "ZZ/S_KARN", DisplayName = "ZZ/S_KARN – zmiana zm. sankcji karnej" } },
			{ "ZZTIRzmianazmtir", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Tiret, ShortCode = "ZZ/TIR", DisplayName = "ZZ/TIR – zmiana zm. tir." } },
			{ "ZZTIRwLITzmianazmtirwlit", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Letter, ShortCode = "ZZ/TIR_w_LIT", DisplayName = "ZZ/TIR_w_LIT – zmiana zm. tir. w lit." } },
			{ "ZZTIRwPKTzmianazmtirwpkt", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Tiret, ParentContext = AmendmentTargetKind.Point, ShortCode = "ZZ/TIR_w_PKT", DisplayName = "ZZ/TIR_w_PKT – zmiana zm. tir. w pkt" } },
			{ "ZZTYTDZOZNzmianazmozntytuudziauartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "ZZ/TYT(DZ)_OZN", DisplayName = "ZZ/TYT(DZ)_OZN – zmiana zm. ozn. tytułu (działu) artykułem (punktem)" } },
			{ "ZZTYTDZPRZEDMzmianazmprzedmtytuulubdziauartykuempunktem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.SystematizingUnit, ShortCode = "ZZ/TYT(DZ)_PRZEDM", DisplayName = "ZZ/TYT(DZ)_PRZEDM – zmiana zm. przedm. tytułu lub działu artykułem (punktem)" } },
			{ "ZZUSTzmianazmust", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Paragraph, ShortCode = "ZZ/UST(§)", DisplayName = "ZZ/UST(§) – zmiana zm. ust. (§)" } },
			{ "ZZWMATFIZCHEMzmwzorumatfizlubchem", new AmendmentStyleInfo { Instrument = AmendmentInstrument.Nested, TargetKind = AmendmentTargetKind.Formula, ShortCode = "ZZ/W_MAT(FIZ|CHEM)", DisplayName = "ZZ/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.)" } }
		};

		/// <summary>
		/// Zwraca statycznie zapisane metadane stylu nowelizacyjnego.
		/// Prosty lookup w <see cref="AmendmentStyleInfoMap"/> — bez parsowania.
		/// </summary>
		public static AmendmentStyleInfo? TryGetAmendmentStyleInfo(string? styleId)
		{
			if (string.IsNullOrWhiteSpace(styleId))
				return null;

			return AmendmentStyleInfoMap.TryGetValue(styleId, out var info) ? info : null;
		}

        public static bool TryGetStyleInfo(string? openXmlStyleId, out StyleInfo? info)
        {
            info = null;
            if (string.IsNullOrWhiteSpace(openXmlStyleId))
            {
                return false;
            }

            if (!StyleMap.TryGetValue(openXmlStyleId, out var displayName))
            {
                return false;
            }

            info = new StyleInfo(displayName, IsAmendmentDisplayName(displayName));
            return true;
        }

        public static string? TryGetOriginalStyleName(string? openXmlStyleId)
        {
            if (string.IsNullOrWhiteSpace(openXmlStyleId))
                return null;

            return StyleMap.TryGetValue(openXmlStyleId, out var name) ? name : null;
        }

        private static bool IsAmendmentDisplayName(string displayName)
        {
            if (string.IsNullOrWhiteSpace(displayName))
            {
                return false;
            }

            return displayName.StartsWith("Z/", StringComparison.OrdinalIgnoreCase)
                || displayName.StartsWith("ZZ/", StringComparison.OrdinalIgnoreCase)
                || displayName.StartsWith("Z_", StringComparison.OrdinalIgnoreCase);
        }
    }
}
