using System;
using System.Collections.Generic;

namespace WordParserLibrary
{
	public static class StyleLibraryMapper
	{
		public static readonly IReadOnlyDictionary<string, string> StyleMap = 
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "2TIRpodwjnytiret", "2TIR – podwójny tiret" },
            { "ARTartustawynprozporzdzenia", "ART(§) – art. ustawy (§ np. rozporządzenia)" },
            { "BEZWERSALIKW", "_BEZ_WERSALIKÓW_" },
            { "CYTcytatnpprzysigi", "CYT – cytat np. przysięgi" },
            { "CZKSIGAoznaczenieiprzedmiotczcilubksigi", "CZĘŚĆ(KSIĘGA) – oznaczenie i przedmiot części lub księgi" },
            { "CZWSP2TIRczwsplnapodwjnychtiret", "CZ_WSP_2TIR – część wspólna podwójnych tiret" },
            { "CZWSPLITODNONIKAczwspliterodnonika", "CZ_WSP_LIT_ODNOŚNIKA – część wsp. liter odnośnika" },
            { "CZWSPLITczwsplnaliter", "CZ_WSP_LIT – część wspólna liter" },
            { "CZWSPP1wTABELIczwsppoziomu1numeracjiwtabeli", "CZ_WSP_P1_w_TABELI – część wsp. poziomu 1 numeracji w tabeli" },
            { "CZWSPP2wTABELIczwsppoziomu2numeracjiwtabeli", "CZ_WSP_P2_w_TABELI – część wsp. poziomu 2 numeracji w tabeli" },
            { "CZWSPP3wTABELIczwsppoziomu3numeracjiwtabeli", "CZ_WSP_P3_w_TABELI – część wsp. poziomu 3 numeracji w tabeli" },
            { "CZWSPP4wTABELIczwsppoziomu4numeracjiwtabeli", "CZ_WSP_P4_w_TABELI – część wsp. poziomu 4 numeracji w tabeli" },
            { "CZWSPPKTODNONIKAczwsppunkwodnonika", "CZ_WSP_PKT_ODNOŚNIKA – część wsp. punków odnośnika" },
            { "CZWSPPKTczwsplnapunktw", "CZ_WSP_PKT – część wspólna punktów" },
            { "CZWSPPPKTOTJczwsppodpunktwwobwieszczeniutekstujednolitego", "CZ_WSP_PPKT_OTJ – część wsp. podpunktów w obwieszczeniu tekstu jednolitego" },
            { "CZWSPTIRczwsplnatiret", "CZ_WSP_TIR – część wspólna tiret" },
            { "DATAAKTUdatauchwalenialubwydaniaaktu", "DATA_AKTU – data uchwalenia lub wydania aktu" },
            { "DATAOTJdatawydaniaobwieszczeniatekstujednolitego", "DATA_OTJ – data wydania obwieszczenia tekstu jednolitego" },
            { "IDKindeksdolnyikursywa", "_ID_K_ – indeks dolny i kursywa" },
            { "IDPKindeksdolnyipogrugieniekursywa", "_ID_P_K_ – indeks dolny i pogrugienie kursywa" },
            { "IDPindeksdolnyipogrubienie", "_ID_P_ – indeks dolny i pogrubienie" },
            { "IDindeksdolny", "_ID_ – indeks dolny" },
            { "IGKindeksgrnyikursywa", "_IG_K_ – indeks górny i kursywa" },
            { "IGPKindeksgrnyipogrubieniekursywa", "_IG_P_K_ – indeks górny i pogrubienie kursywa" },
            { "IGPindeksgrnyipogrubienie", "_IG_P_ – indeks górny i pogrubienie" },
            { "IGindeksgrny", "_IG_ – indeks górny" },
            { "IIGPindeksgrnyindeksugrnegoipogrubienie", "_IIG_P_ – indeks górny indeksu górnego i pogrubienie" },
            { "IIGindeksgrnyindeksugrnego", "_IIG_ – indeks górny indeksu górnego" },
            { "Kkursywa", "_K_ – kursywa" },
            { "LEGWMATFIZCHEMlegendawzorumatfizlubchem", "LEG_W_MAT(FIZ|CHEM) – legenda wzoru mat. (fiz. lub chem.)" },
            { "LITODNONIKAliteraodnonika", "LIT_ODNOŚNIKA – litera odnośnika" },
            { "LITlitera", "LIT – litera" },
            { "NAZORGWPOROZUMIENIUnazwaorganuwporozumieniuzktrymaktjestwydawany", "NAZ_ORG_W_POROZUMIENIU – nazwa organu w porozumieniu z którym akt jest wydawany" },
            { "NAZORGWYDnazwaorganuwydajcegoprojektowanyakt", "NAZ_ORG_WYD – nazwa organu wydającego projektowany akt" },
            { "NIEARTTEKSTtekstnieartykuowanynppodstprawnarozplubpreambua", "NIEART_TEKST – tekst nieartykułowany (np. podst. prawna rozp. lub preambuła)" },
            { "ODNONIKSPECtreodnonikadoodnonika", "ODNOŚNIK_SPEC – treść odnośnika do odnośnika" },
            { "ODNONIKtreodnonika", "ODNOŚNIK – treść odnośnika" },
            { "OZNPROJEKTUwskazaniedatylubwersjiprojektu", "OZN_PROJEKTU – wskazanie daty lub wersji projektu" },
            { "OZNRODZAKTUtznustawalubrozporzdzenieiorganwydajcy", "OZN_RODZ_AKTU – tzn. ustawa lub rozporządzenie i organ wydający" },
            { "OZNZACZNIKAwskazanienrzacznika", "OZN_ZAŁĄCZNIKA – wskazanie nr załącznika" },
            { "P1wTABELIpoziom1numeracjiwtabeli", "P1_w_TABELI – poziom 1 numeracji w tabeli" },
            { "P2wTABELIpoziom2numeracjiwtabeli", "P2_w_TABELI – poziom 2 numeracji w tabeli" },
            { "P3wTABELIpoziom3numeracjiwtabeli", "P3_w_TABELI – poziom 3 numeracji w tabeli" },
            { "P4wTABELIpoziom4numeracjiwtabeli", "P4_w_TABELI – poziom 4 numeracji w tabeli" },
            { "PKTODNONIKApunktodnonika", "PKT_ODNOŚNIKA – punkt odnośnika" },
            { "PKTOTJpunktobwieszczeniatekstujednolitegonp1", "PKT_OTJ – punkt obwieszczenia tekstu jednolitego np. \"1.\"" },
            { "PKTpunkt", "PKT – punkt" },
            { "PKpogrubieniekursywa", "_P_K_ – pogrubienie kursywa" },
            { "PPKTOTJpodpunktwobwieszczeniutekstujednolitegonp1", "PPKT_OTJ – podpunkt w obwieszczeniu tekstu jednolitego np. \"1)\"" },
            { "Ppogrubienie", "_P_ – pogrubienie" },
            { "ROZDZODDZOZNoznaczenierozdziauluboddziau", "ROZDZ(ODDZ)_OZN – oznaczenie rozdziału lub oddziału" },
            { "ROZDZODDZPRZEDMprzedmiotregulacjirozdziauluboddziau", "ROZDZ(ODDZ)_PRZEDM – przedmiot regulacji rozdziału lub oddziału" },
            { "SKARNsankcjakarnawszczeglnociwKodeksiekarnym", "S_KARN – sankcja karna w szczególności w Kodeksie karnym" },
            { "TEKSTwTABELIWYRODKOWANYtekstwyrodkowanywpoziomie", "TEKST_w_TABELI_WYŚRODKOWANY – tekst wyśrodkowany w poziomie" },
            { "TEKSTwTABELItekstzwcitympierwwierszem", "TEKST_w_TABELI – tekst z wciętym pierw. wierszem" },
            { "TIRtiret", "TIR – tiret" },
            { "TYTDZOZNoznaczenietytuulubdziau", "TYT(DZ)_OZN – oznaczenie tytułu lub działu" },
            { "TYTDZPRZEDMprzedmiotregulacjitytuulubdziau", "TYT(DZ)_PRZEDM – przedmiot regulacji tytułu lub działu" },
            { "TYTTABELItytutabeli", "TYT_TABELI – tytuł tabeli" },
            { "TYTUAKTUprzedmiotregulacjiustawylubrozporzdzenia", "TYTUŁ_AKTU – przedmiot regulacji ustawy lub rozporządzenia" },
            { "TYTUOTJprzedmiotobwieszczeniatekstujednolitego", "TYTUŁ_OTJ – przedmiot obwieszczenia tekstu jednolitego" },
            { "USTustnpkodeksu", "UST(§) – ust. (§ np. kodeksu)" },
            { "WMATFIZCHEMwzrmatfizlubchem", "W_MAT(FIZ|CHEM) – wzór mat. (fiz. lub chem.)" },
            { "Z2TIR2TIRwLITzmpodwtirwlitpodwjnymtiret", "Z_2TIR/2TIR_w_LIT – zm. podw. tir. w lit. podwójnym tiret" },
            { "Z2TIR2TIRwPKTzmpodwtirwpktpodwjnymtiret", "Z_2TIR/2TIR_w_PKT – zm. podw. tir. w pkt podwójnym tiret" },
            { "Z2TIR2TIRwTIRzmpodwtirwtirpodwjnymtiret", "Z_2TIR/2TIR_w_TIR – zm. podw. tir. w tir. podwójnym tiret" },
            { "Z2TIR2TIRzmpodwtirpodwjnymtiret", "Z_2TIR/2TIR – zm. podw. tir. podwójnym tiret" },
            { "Z2TIRARTzmartpodwjnymtiret", "Z_2TIR/ART(§) – zm. art. (§) podwójnym tiret" },
            { "Z2TIRCYTzmcytatunpprzysigipodwjnymtiret", "Z_2TIR/CYT – zm. cytatu np. przysięgi podwójnym tiret" },
            { "Z2TIRCZWSP2TIRwLITzmczciwsppodwtirwlitpodwjnymtiret", "Z_2TIR/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. podwójnym tiret" },
            { "Z2TIRCZWSP2TIRwPKTzmczciwsppodwtirwpktpodwjnymtiret", "Z_2TIR/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt podwójnym tiret" },
            { "Z2TIRCZWSP2TIRwTIRzmczciwsppodwtirwtiretpodwjnymtiret", "Z_2TIR/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tiret podwójnym tiret" },
            { "Z2TIRCZWSP2TIRzmczciwsppodwtirpodwjnymtiret", "Z_2TIR/CZ_WSP_2TIR – zm. części wsp. podw. tir. podwójnym tiret" },
            { "Z2TIRCZWSPLITwPKTzmczciwsplitwpktpodwjnymtiret", "Z_2TIR/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt podwójnym tiret" },
            { "Z2TIRCZWSPLITzmczciwsplitpodwjnymtiret", "Z_2TIR/CZ_WSP_LIT – zm. części wsp. lit. podwójnym tiret" },
            { "Z2TIRCZWSPPKTzmczciwsppktpodwjnymtiret", "Z_2TIR/CZ_WSP_PKT – zm. części wsp. pkt podwójnym tiret" },
            { "Z2TIRCZWSPTIRwLITzmczciwsptirwlitpodwjnymtiret", "Z_2TIR/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. podwójnym tiret" },
            { "Z2TIRCZWSPTIRwPKTzmczciwsptirwpktpodwjnymtiret", "Z_2TIR/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt podwójnym tiret" },
            { "Z2TIRCZWSPTIRzmczciwsptirpodwjnymtiret", "Z_2TIR/CZ_WSP_TIR – zm. części wsp. tir. podwójnym tiret" },
            { "Z2TIRFRAGMzmnpwprdowyliczeniapodwjnymtiret", "Z_2TIR/FRAGM – zm. np. wpr. do wyliczenia podwójnym tiret" },
            { "Z2TIRLEGWMATFIZCHEMzmlegendywzorumatfizlubchempodwjnymtiret", "Z_2TIR/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) podwójnym tiret" },
            { "Z2TIRLITwPKTzmlitwpktpodwjnymtiret", "Z_2TIR/LIT_w_PKT – zm. lit. w pkt podwójnym tiret" },
            { "Z2TIRLITzmlitpodwjnymtiret", "Z_2TIR/LIT – zm. lit. podwójnym tiret" },
            { "Z2TIRPKTzmpktpodwjnymtiret", "Z_2TIR/PKT – zm. pkt podwójnym tiret" },
            { "Z2TIRROZDZODDZOZNzmoznrozdzoddzpodwjnymtiret", "Z_2TIR/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) podwójnym tiret" },
            { "Z2TIRROZDZODDZPRZEDMzmprzedmrozdzoddzpodwjnymtiret", "Z_2TIR/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) podwójnym tiret" },
            { "Z2TIRSKARNzmianasankcjikarnejpodwjnymtiret", "Z_2TIR/S_KARN – zmiana sankcji karnej podwójnym tiret" },
            { "Z2TIRTIRwLITzmtirwlitpodwjnymtiret", "Z_2TIR/TIR_w_LIT – zm. tir. w lit. podwójnym tiret" },
            { "Z2TIRTIRwPKTzmtirwpktpodwjnymtiret", "Z_2TIR/TIR_w_PKT – zm. tir. w pkt podwójnym tiret" },
            { "Z2TIRTIRzmtirpodwjnymtiret", "Z_2TIR/TIR – zm. tir. podwójnym tiret" },
            { "Z2TIRUSTzmustpodwjnymtiret", "Z_2TIR/UST(§) – zm. ust. (§) podwójnym tiret" },
            { "Z2TIRWMATFIZCHEMzmwzorumatfizlubchempodwjnymtiret", "Z_2TIR/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) podwójnym tiret" },
            { "Z2TIRwLITzmpodwtirwlitartykuempunktem", "Z/2TIR_w_LIT – zm. podw. tir. w lit. artykułem (punktem)" },
            { "Z2TIRwPKTzmpodwtirwpktartykuempunktem", "Z/2TIR_w_PKT – zm. podw. tir. w pkt artykułem (punktem)" },
            { "Z2TIRwTIRzmpodwtirwtirartykuempunktem", "Z/2TIR_w_TIR – zm. podw. tir. w tir. artykułem (punktem)" },
            { "Z2TIRzmpodwtirartykuempunktem", "Z/2TIR – zm. podw. tir. artykułem (punktem)" },
            { "ZARTzmartartykuempunktem", "Z/ART(§) – zm. art. (§) artykułem (punktem)" },
            { "ZCYTzmcytatunpprzysigiartykuempunktem", "Z/CYT – zm. cytatu np. przysięgi artykułem (punktem)" },
            { "ZCZCIKSIGIzmozniprzedmczciksigiartykuempunktem", "Z/CZĘŚCI(KSIĘGI) – zm. ozn. i przedm. części (księgi) artykułem (punktem)" },
            { "ZCZWSP2TIRwLITzmczciwsppodwtirwlitartykuempunktem", "Z/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. artykułem (punktem)" },
            { "ZCZWSP2TIRwPKTzmczciwsppodwtirwpktartykuempunktem", "Z/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt artykułem (punktem)" },
            { "ZCZWSP2TIRwTIRzmczciwsppodwtirwtirartykuempunktem", "Z/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. artykułem (punktem)" },
            { "ZCZWSP2TIRzmczciwsplnejpodwtirartykuempunktem", "Z/CZ_WSP_2TIR – zm. części wspólnej podw. tir. artykułem (punktem)" },
            { "ZCZWSPLITODNONIKAzmczciwsplitodnonikaartykuempunktem", "Z/CZ_WSP_LIT_ODNOŚNIKA – zm. części wsp. lit odnośnika artykułem (punktem)" },
            { "ZCZWSPLITwPKTODNONIKAzmczciwsplitwpktodnonikaartykuempunktem", "Z/CZ_WSP_LIT_w_PKT_ODNOŚNIKA – zm. części wsp. lit. w pkt odnośnika artykułem (punktem)" },
            { "ZCZWSPLITwPKTwODNONIKUzmczciwsplitwpktwzmienianymodnonikuartykuempunktem", "Z/CZ_WSP_LIT_w_PKT_w_ODNOŚNIKU – zm. części wsp. lit. w pkt w zmienianym odnośniku artykułem (punktem)" },
            { "ZCZWSPLITwPKTzmczciwsplitwpktartykuempunktem", "Z/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt artykułem (punktem)" },
            { "ZCZWSPLITzmczciwsplitartykuempunktem", "Z/CZ_WSP_LIT – zm. części wsp. lit. artykułem (punktem)" },
            { "ZCZWSPPKTODNONIKAzmczciwsppktodnonikaartykuempunktem", "Z/CZ_WSP_PKT_ODNOŚNIKA – zm. części wsp. pkt odnośnika artykułem (punktem)" },
            { "ZCZWSPPKTwODNONIKUzmczciwsppktwzmienianymodnonikuartykuempunktem", "Z/CZ_WSP_PKT_w_ODNOŚNIKU – zm. części wsp. pkt w zmienianym odnośniku artykułem (punktem)" },
            { "ZCZWSPPKTzmczciwsppktartykuempunktem", "Z/CZ_WSP_PKT – zm. części wsp. pkt artykułem (punktem)" },
            { "ZCZWSPTIRwLITzmczciwsptirwlitartykuempunktem", "Z/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. artykułem (punktem)" },
            { "ZCZWSPTIRwPKTzmczciwsptirwpktartykuempunktem", "Z/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt artykułem (punktem)" },
            { "ZCZWSPTIRzmczciwsptirartykuempunktem", "Z/CZ_WSP_TIR – zm. części wsp. tir. artykułem (punktem)" },
            { "ZDANIENASTNOWYWIERSZODNONIKAnpzddrugienowywiersz", "ZDANIE_NAST_NOWY_WIERSZ_ODNOŚNIKA – np. zd. drugie (nowy wiersz)" },
            { "ZDANIENASTNOWYWIERSZnpzddrugienowywierszwust", "ZDANIE_NAST_NOWY_WIERSZ – np. zd. drugie (nowy wiersz) w ust." },
            { "ZFRAGzmfragmentunpzdaniaartykuempunktem", "Z/FRAG – zm. fragmentu (np. zdania) artykułem (punktem)" },
            { "ZLEGWMATFIZCHEMzmlegendywzorumatfizlubchemartykuempunktem", "Z/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) artykułem (punktem)" },
            { "ZLIT2TIRwLITzmpodwtirwlitliter", "Z_LIT/2TIR_w_LIT – zm. podw. tir. w lit. literą" },
            { "ZLIT2TIRwPKTzmpodwtirwpktliter", "Z_LIT/2TIR_w_PKT – zm. podw. tir. w pkt literą" },
            { "ZLIT2TIRwTIRzmpodwtirwtirliter", "Z_LIT/2TIR_w_TIR – zm. podw. tir. w tir. literą" },
            { "ZLIT2TIRzmpodwtirliter", "Z_LIT/2TIR – zm. podw. tir. literą" },
            { "ZLITARTzmartliter", "Z_LIT/ART(§) – zm. art. (§) literą" },
            { "ZLITCYTzmcytatunpprzysigiliter", "Z_LIT/CYT – zm. cytatu np. przysięgi literą" },
            { "ZLITCZWSP2TIRwLITzmczciwsppodwtirwlitliter", "Z_LIT/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. literą" },
            { "ZLITCZWSP2TIRwPKTzmczciwsppodwtirwpktliter", "Z_LIT/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt literą" },
            { "ZLITCZWSP2TIRwTIRzmczciwsppodwtirwtirliter", "Z_LIT/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. literą" },
            { "ZLITCZWSP2TIRzmczciwsppodwtirliter", "Z_LIT/CZ_WSP_2TIR – zm. części wsp. podw. tir. literą" },
            { "ZLITCZWSPLITwPKTzmczciwsplitwpktliter", "Z_LIT/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt literą" },
            { "ZLITCZWSPLITzmczciwsplitliter", "Z_LIT/CZ_WSP_LIT – zm. części wsp. lit. literą" },
            { "ZLITCZWSPPKTzmczciwsppktliter", "Z_LIT/CZ_WSP_PKT – zm. części wsp. pkt literą" },
            { "ZLITCZWSPTIRwLITzmczciwsptirwlitliter", "Z_LIT/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. literą" },
            { "ZLITCZWSPTIRwPKTzmczciwsptirwpktliter", "Z_LIT/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. w pkt literą" },
            { "ZLITCZWSPTIRzmczciwsptirliter", "Z_LIT/CZ_WSP_TIR – zm. części wsp. tir. literą" },
            { "ZLITFRAGzmlitfragmentunpzdanialiter", "Z_LIT/FRAG – zm. lit. fragmentu (np. zdania) literą" },
            { "ZLITKSIGIzmozniprzedmksigiliter", "Z_LIT/KSIĘGI – zm. ozn. i przedm. księgi literą" },
            { "ZLITLEGWMATFIZCHEMzmlegendywzorumatfizlubchemliter", "Z_LIT/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) literą" },
            { "ZLITLITwPKTzmlitwpktliter", "Z_LIT/LIT_w_PKT – zm. lit. w pkt literą" },
            { "ZLITLITzmlitliter", "Z_LIT/LIT – zm. lit. literą" },
            { "ZLITODNONIKAzmlitodnonikaartykuempunktem", "Z/LIT_ODNOŚNIKA – zm. lit. odnośnika artykułem (punktem)" },
            { "ZLITPKTzmpktliter", "Z_LIT/PKT – zm. pkt literą" },
            { "ZLITROZDZODDZOZNzmoznrozdzoddzliter", "Z_LIT/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) literą" },
            { "ZLITROZDZODDZPRZEDMzmprzedmrozdzoddzliter", "Z_LIT/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) literą" },
            { "ZLITSKARNzmsankcjikarnejliter", "Z_LIT/S_KARN – zm. sankcji karnej literą" },
            { "ZLITTIRwLITzmtirwlitliter", "Z_LIT/TIR_w_LIT – zm. tir. w lit. literą" },
            { "ZLITTIRwPKTzmtirwpktliter", "Z_LIT/TIR_w_PKT – zm. tir. w pkt literą" },
            { "ZLITTIRzmtirliter", "Z_LIT/TIR – zm. tir. literą" },
            { "ZLITTYTDZOZNzmozntytuudziauliter", "Z_LIT/TYT(DZ)_OZN – zm. ozn. tytułu (działu) literą" },
            { "ZLITTYTDZPRZEDMzmprzedmtytuudziauliter", "Z_LIT/TYT(DZ)_PRZEDM – zm. przedm. tytułu (działu) literą" },
            { "ZLITUSTzmustliter", "Z_LIT/UST(§) – zm. ust. (§) literą" },
            { "ZLITWMATFIZCHEMzmwzorumatfizlubchemliter", "Z_LIT/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) literą" },
            { "ZLITwPKTODNONIKAzmlitwpktodnonikaartykuempunktem", "Z/LIT_w_PKT_ODNOŚNIKA – zm. lit. w pkt odnośnika artykułem (punktem)" },
            { "ZLITwPKTwODNONIKUzmlitwpktwzmienianymodnonikuartykuempunktem", "Z/LIT_w_PKT_w_ODNOŚNIKU – zm. lit. w pkt w zmienianym odnośniku artykułem (punktem)" },
            { "ZLITwPKTzmlitwpktartykuempunktem", "Z/LIT_w_PKT – zm. lit. w pkt artykułem (punktem)" },
            { "ZLITzmlitartykuempunktem", "Z/LIT – zm. lit. artykułem (punktem)" },
            { "ZNIEARTTEKSTzmtekstunieartykuowanego", "Z/NIEART_TEKST – zm. tekstu nieartykułowanego" },
            { "ZODNONIKAzmtekstuodnonikaartykuempunktem", "Z/ODNOŚNIKA – zm. tekstu odnośnika artykułem (punktem)" },
            { "ZPKTODNONIKAzmpktodnonikaartykuempunktem", "Z/PKT_ODNOŚNIKA – zm. pkt odnośnika artykułem (punktem)" },
            { "ZPKTwODNONIKUzmpktwzmienianymodnonikuartykuempunktem", "Z/PKT_w_ODNOŚNIKU – zm. pkt w zmienianym odnośniku artykułem (punktem)" },
            { "ZPKTzmpktartykuempunktem", "Z/PKT – zm. pkt artykułem (punktem)" },
            { "ZROZDZODDZOZNzmoznrozdzoddzartykuempunktem", "Z/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) artykułem (punktem)" },
            { "ZROZDZODDZPRZEDMzmprzedmrozdzoddzartykuempunktem", "Z/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) artykułem (punktem)" },
            { "ZSKARNzmsankcjikarnejwszczeglnociwKodeksiekarnym", "Z/S_KARN – zm. sankcji karnej w szczególności w Kodeksie karnym" },
            { "ZTIR2TIRwLITzmpodwtirwlittiret", "Z_TIR/2TIR_w_LIT – zm. podw. tir. w lit. tiret" },
            { "ZTIR2TIRwPKTzmpodwtirwpkttiret", "Z_TIR/2TIR_w_PKT – zm. podw. tir. w pkt tiret" },
            { "ZTIR2TIRwTIRzmpodwtirwtirtiret", "Z_TIR/2TIR_w_TIR – zm. podw. tir. w tir. tiret" },
            { "ZTIR2TIRzmpodwtirtiret", "Z_TIR/2TIR – zm. podw. tir. tiret" },
            { "ZTIRARTzmarttiret", "Z_TIR/ART(§) – zm. art. (§) tiret" },
            { "ZTIRCYTzmcytatunpprzysigitiret", "Z_TIR/CYT – zm. cytatu np. przysięgi tiret" },
            { "ZTIRCZWSP2TIRwLITzmczciwsppodwtirwlittiret", "Z_TIR/CZ_WSP_2TIR_w_LIT – zm. części wsp. podw. tir. w lit. tiret" },
            { "ZTIRCZWSP2TIRwPKTzmczciwsppodwtirwpkttiret", "Z_TIR/CZ_WSP_2TIR_w_PKT – zm. części wsp. podw. tir. w pkt tiret" },
            { "ZTIRCZWSP2TIRwTIRzmczciwsppodwtirwtirtiret", "Z_TIR/CZ_WSP_2TIR_w_TIR – zm. części wsp. podw. tir. w tir. tiret" },
            { "ZTIRCZWSP2TIRzmczciwsppodwtirtiret", "Z_TIR/CZ_WSP_2TIR – zm. części wsp. podw. tir. tiret" },
            { "ZTIRCZWSPLITwPKTzmczciwsplitwpkttiret", "Z_TIR/CZ_WSP_LIT_w_PKT – zm. części wsp. lit. w pkt tiret" },
            { "ZTIRCZWSPLITzmczciwsplittiret", "Z_TIR/CZ_WSP_LIT – zm. części wsp. lit. tiret" },
            { "ZTIRCZWSPPKTzmczciwsppkttiret", "Z_TIR/CZ_WSP_PKT – zm. części wsp. pkt tiret" },
            { "ZTIRCZWSPTIRwLITzmczciwsptirwlittiret", "Z_TIR/CZ_WSP_TIR_w_LIT – zm. części wsp. tir. w lit. tiret" },
            { "ZTIRCZWSPTIRwPKTzmczciwsptirtiret", "Z_TIR/CZ_WSP_TIR_w_PKT – zm. części wsp. tir. tiret" },
            { "ZTIRCZWSPTIRzmczciwsptirtiret", "Z_TIR/CZ_WSP_TIR – zm. części wsp. tir. tiret" },
            { "ZTIRDZOZNzmozndziautiret", "Z_TIR/DZ_OZN – zm. ozn. działu tiret" },
            { "ZTIRDZPRZEDMzmprzedmdziautiret", "Z_TIR/DZ_PRZEDM – zm. przedm. działu tiret" },
            { "ZTIRFRAGMzmnpwprdowyliczeniatiret", "Z_TIR/FRAGM – zm. np. wpr. do wyliczenia tiret" },
            { "ZTIRLEGWMATFIZCHEMzmlegendywzorumatfizlubchemtiret", "Z_TIR/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.) tiret" },
            { "ZTIRLITwPKTzmlitwpkttiret", "Z_TIR/LIT_w_PKT – zm. lit. w pkt tiret" },
            { "ZTIRLITzmlittiret", "Z_TIR/LIT – zm. lit. tiret" },
            { "ZTIRPKTzmpkttiret", "Z_TIR/PKT – zm. pkt tiret" },
            { "ZTIRROZDZODDZOZNzmoznrozdzoddztiret", "Z_TIR/ROZDZ(ODDZ)_OZN – zm. ozn. rozdz. (oddz.) tiret" },
            { "ZTIRROZDZODDZPRZEDMzmprzedmrozdzoddztiret", "Z_TIR/ROZDZ(ODDZ)_PRZEDM – zm. przedm. rozdz. (oddz.) tiret" },
            { "ZTIRSKARNzmsankcjikarnejtiret", "Z_TIR/S_KARN – zm. sankcji karnej tiret" },
            { "ZTIRTIRwLITzmtirwlittiret", "Z_TIR/TIR_w_LIT – zm. tir. w lit. tiret" },
            { "ZTIRTIRwPKTzmtirwpkttiret", "Z_TIR/TIR_w_PKT – zm. tir. w pkt tiret" },
            { "ZTIRTIRzmtirtiret", "Z_TIR/TIR – zm. tir. tiret" },
            { "ZTIRUSTzmusttiret", "Z_TIR/UST(§) – zm. ust. (§) tiret" },
            { "ZTIRWMATFIZCHEMzmwzorumatfizlubchemtiret", "Z_TIR/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) tiret" },
            { "ZTIRwLITzmtirwlitartykuempunktem", "Z/TIR_w_LIT – zm. tir. w lit. artykułem (punktem)" },
            { "ZTIRwPKTzmtirwpktartykuempunktem", "Z/TIR_w_PKT – zm. tir. w pkt artykułem (punktem)" },
            { "ZTIRzmtirartykuempunktem", "Z/TIR – zm. tir. artykułem (punktem)" },
            { "ZTYTDZOZNzmozntytuudziauartykuempunktem", "Z/TYT(DZ)_OZN – zm. ozn. tytułu (działu) artykułem (punktem)" },
            { "ZTYTDZPRZEDMzmprzedmtytuulubdziauartykuempunktem", "Z/TYT(DZ)_PRZEDM – zm. przedm. tytułu lub działu artykułem (punktem)" },
            { "ZUSTzmustartykuempunktem", "Z/UST(§) – zm. ust. (§) artykułem (punktem)" },
            { "ZWMATFIZCHEMzmwzorumatfizlubchemartykuempunktem", "Z/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.) artykułem (punktem)" },
            { "ZZ2TIRwLITzmianazmpodwtirwlit", "ZZ/2TIR_w_LIT – zmiana zm. podw. tir. w lit." },
            { "ZZ2TIRwPKTzmianazmpodwtirwpkt", "ZZ/2TIR_w_PKT – zmiana zm. podw. tir. w pkt" },
            { "ZZ2TIRwTIRzmianazmpodwtirwtir", "ZZ/2TIR_w_TIR – zmiana zm. podw. tir. w tir." },
            { "ZZ2TIRzmianazmpodwtir", "ZZ/2TIR – zmiana zm. podw. tir." },
            { "ZZARTzmianazmart", "ZZ/ART(§) – zmiana zm. art. (§)" },
            { "ZZCYTzmianazmcytatunpprzysigi", "ZZ/CYT – zmiana zm. cytatu np. przysięgi" },
            { "ZZCZCIKSIGIzmianazmozniprzedmczciksigiartykuempunktem", "ZZ/CZĘŚCI(KSIĘGI) – zmiana zm. ozn. i przedm. części (księgi) artykułem (punktem)" },
            { "ZZCZWSP2TIRwLITzmianazmczciwsppodwtirwlit", "ZZ/CZ_WSP_2TIR_w_LIT – zmiana zm. części wsp. podw. tir. w lit." },
            { "ZZCZWSP2TIRwPKTzmianazmczciwsppodwtirwpkt", "ZZ/CZ_WSP_2TIR_w_PKT – zmiana zm. części wsp. podw. tir. w pkt" },
            { "ZZCZWSP2TIRwTIRzmianazmczciwsppodwtirwtir", "ZZ/CZ_WSP_2TIR_w_TIR – zmiana zm. części wsp. podw. tir. w tir." },
            { "ZZCZWSP2TIRzmianazmczciwsppodwtir", "ZZ/CZ_WSP_2TIR – zmiana zm. części wsp. podw. tir." },
            { "ZZCZWSPLITwPKTzmianazmczciwsplitwpkt", "ZZ/CZ_WSP_LIT_w_PKT – zmiana zm. części wsp. lit. w pkt" },
            { "ZZCZWSPLITzmianazmczciwsplit", "ZZ/CZ_WSP_LIT – zmiana. zm. części wsp. lit." },
            { "ZZCZWSPPKTzmianazmczciwsppkt", "ZZ/CZ_WSP_PKT – zmiana. zm. części wsp. pkt" },
            { "ZZCZWSPTIRwLITzmianazmczciwsptirwlit", "ZZ/CZ_WSP_TIR_w_LIT – zmiana zm. części wsp. tir. w lit." },
            { "ZZCZWSPTIRwPKTzmianazmczciwsptirwpkt", "ZZ/CZ_WSP_TIR_w_PKT – zmiana zm. części wsp. tir. w pkt" },
            { "ZZCZWSPTIRzmianazmczciwsptir", "ZZ/CZ_WSP_TIR – zmiana. zm. części wsp. tir." },
            { "ZZFRAGzmianazmfragmentunpzdania", "ZZ/FRAG – zmiana zm. fragmentu (np. zdania)" },
            { "ZZLEGWMATFIZCHEMzmlegendywzorumatfizlubchem", "ZZ/LEG_W_MAT(FIZ|CHEM) – zm. legendy wzoru mat. (fiz. lub chem.)" },
            { "ZZLITwPKTzmianazmlitwpkt", "ZZ/LIT_w_PKT – zmiana zm. lit. w pkt" },
            { "ZZLITzmianazmlit", "ZZ/LIT – zmiana zm. lit." },
            { "ZZPKTzmianazmpkt", "ZZ/PKT – zmiana zm. pkt" },
            { "ZZROZDZODDZOZNzmianazmoznrozdzoddzartykuempunktem", "ZZ/ROZDZ(ODDZ)_OZN – zmiana zm. ozn. rozdz. (oddz.) artykułem (punktem)" },
            { "ZZROZDZODDZPRZEDMzmianazmprzedmrozdzoddzartykuempunktem", "ZZ/ROZDZ(ODDZ)_PRZEDM – zmiana zm. przedm. rozdz. (oddz.) artykułem (punktem)" },
            { "ZZSKARNzmianazmsankcjikarnej", "ZZ/S_KARN – zmiana zm. sankcji karnej" },
            { "ZZTIRwLITzmianazmtirwlit", "ZZ/TIR_w_LIT – zmiana zm. tir. w lit." },
            { "ZZTIRwPKTzmianazmtirwpkt", "ZZ/TIR_w_PKT – zmiana zm. tir. w pkt" },
            { "ZZTIRzmianazmtir", "ZZ/TIR – zmiana zm. tir." },
            { "ZZTYTDZOZNzmianazmozntytuudziauartykuempunktem", "ZZ/TYT(DZ)_OZN – zmiana zm. ozn. tytułu (działu) artykułem (punktem)" },
            { "ZZTYTDZPRZEDMzmianazmprzedmtytuulubdziauartykuempunktem", "ZZ/TYT(DZ)_PRZEDM – zmiana zm. przedm. tytułu lub działu artykułem (punktem)" },
            { "ZZUSTzmianazmust", "ZZ/UST(§) – zmiana zm. ust. (§)" },
            { "ZZWMATFIZCHEMzmwzorumatfizlubchem", "ZZ/W_MAT(FIZ|CHEM) – zm. wzoru mat. (fiz. lub chem.)" }
        };

        public static string? TryGetOriginalStyleName(string? openXmlStyleId)
        {
            if (string.IsNullOrWhiteSpace(openXmlStyleId))
                return null;

            return StyleMap.TryGetValue(openXmlStyleId, out var name) ? name : null;
        }
    }
}
